### ISSUE TITLE
When using FormKit type radio in a loop, the state is not displayed properly when clicking another in the list.

### ISSUE THREAD

**Issue by fdverwoerd** [formkit/formkit#1029]
### Reproduction

https://formkit.link/bc0d697632a3ecd0c36063530a702759

### Describe the bug

So here is a dynamicly list group. But when clicking add item in list (e.g.) 'geslacht|gender' the model is updated though, but the first item in the list looses the 'selected' value? Why is that?

### Environment

• OS: MacOS sonoma
• Browser firefox
• Version 119

**Comment by GustavoFenilli** [comment]
That is correct, radio's with the same name are linked by html specs. you can use this simple plugin to add an alternative name to your radios: https://formkit.link/a7dd505546e9c3d057a99de968577ea8

But I guess they should be done automatically because they are in a dynamic list, maybe its because they are also inside a group @justin-schroeder?

**Comment by fdverwoerd** [comment]
It seems to be working if I make the name prop unique, but in my case I was expecting that because it is in a group it is 'scoped'.

```
:name="'gender_'+index"
```

**Comment by justin-schroeder** [comment]
Yeah if this was a dynamic list this would be done for you automatically. In a static list though it is expected that you name them uniquely. (notice the list is missing "dynamic"):

<img width="335" alt="image" src="https://github.com/formkit/formkit/assets/1950463/df9f5ac6-1a2e-4030-a6e8-38aeffdb8e07">

Best of luck 👍

**Comment by fdverwoerd** [comment]
Thank you very much! I also added `:index="index"` to make it work.
