### ISSUE TITLE
Inputs in disabled repeaters can't be enabled

### ISSUE THREAD

**Issue by SDRACK** [formkit/formkit#1043]
### Reproduction

https://formkit.link/2c3dc575e1885a91272c5a4e7b204ca5

### Describe the bug

Within a disabled form, individual inputs can be enabled by adding `disabled: false`. However, when these inputs are within a repeater disabled by the form, the input remains locked.

We've a use case where we need to enable a certain field in this manner, but existing in a repeater blocks us from doing so.

See the attached playground for an example of the issue.

### Environment

• OS: Ventura 13.5.1
• Browser Chrome Version 119.0.6045.159
• Version Formkit 1.3

**Comment by SDRACK** [comment]
Thanks for the response @andrew-boyd - I'll admit it's a bit of an odd one, but it's a genuine use case we've got. 

I think the biggest challenge I have with this is consistency - you can see in the playground it's possible to re-enable fields in a disabled for, but not within a repeater. This is what threw me off here :)

If this is something that's unlikely to change we'll find a UI workaround, but my humble opinion is the flexibility is really useful, being able to customise the form fields at an individual level regardless of their parents' status.

Let me know what you think and we'll tinker with things our end as necessary!

**Comment by justin-schroeder** [comment]
Amazing edge case. I think I agree with you @SDRACK that it would be nice for inputs to always respect their own settings over a parents (with some rare exceptions, like `value` which should actually be assigned from the parent rather than the child on initial value, but thats a different conversation).

We’ll see if we can sort this out.

**Comment by justin-schroeder** [comment]
this 100% should just work — we’ll look into it.

**Comment by justin-schroeder** [comment]
@andrew-boyd I made one change to ensure the `data-disabled` prop is gone (not set to `"false"`) — now I think we need to update regenesis to use an alternative group name for the repeater. Are you able to do this?

**Comment by andrew-boyd** [comment]
Working on styling for this but we have an additional issue. `repeater` inputs do not pass the disabled property down to their children like `group` does. We need children to inherit the disabled property so that we can style the repeater in a way that does not enforce a disabled appearance on its children.

playground showing the issue: https://formkit.link/1efab4789f5a64a6d63db6583de40499

**Comment by andrew-boyd** [comment]
Have styling for this queued up for Regenisis and Starter — but because the `repeater` fieldset is no longer getting the `disabled` attribute the repeater action buttons are not being flagged as `disabled`. We can work around this with CSS (`pointer-events-none`) but the _proper_ solution is probably to update the repeater schema to manually put the `disabled` attribute on the action buttons.

**Comment by andrew-boyd** [comment]
@SDRACK This got marked as closed but the updated theme was never published. it's actually fixed now: https://formkit.link/e5e4dab2c9928c27c73b1727aee14b32
