### ISSUE TITLE
Dropdown component: option with `null` value not shown in input when selected

### ISSUE THREAD

**Issue by KoenCa** [formkit/formkit#1054]
### Reproduction

https://formkit.link/e6d2ea00d0aae1c7e3d4a3e0078e98fe

### Describe the bug

The label of a dropdown option with the value `null` doesn't show up when selected, but the value is set as you can see in the reproduction link. The same happens when an empty string `''` or `undefined` is used instead of `null` as a value.

### Environment

• OS: Mac
• Browser: Arc
• Version: 1.3

**Comment by sashamilenkovic** [comment]
@KoenCa Yes! Totally fair thing to point out; it should probably be mentioned in the documentation, as it seems reasonable that assigning the value `null` when you have an option with the value `null` would show that option. 

Essentially, we are considering `""`, `undefined`, and `null` as _empty values_.

So let's take this example: https://formkit.link/414348842dac6dd79cbbec819749ca9f, where we have an autocomplete with the value "Hello World" assigned to it. In this example, there are no options assigned to the autocomplete with the value "Hello World" but we still want to reflect in the UI that the autocomplete has a _non-empty value_ (which I think is important). However, if we were to assign the value `null`, we would not want to make this assumption, that the autocomplete _has a value_, so we wouldn't want to reflect the value `null` in the UI (nor empty string, or undefined).

Another example of why we are ignoring these `empty values` is in instances where the autocomplete is assigned an option loader: https://formkit.link/9173c5f6821b72c635a3f566de0b13c0. In this example, the autocomplete is assigned the value `null`, but because it falls in the category of an `empty value`, we do not want to call the option loader (you can see that the `loadMovie` function is not called). 

You might be wondering, "Well shouldn't `undefined` always be the default, and assigning anything other than `undefined` should be considered a valid value", I would agree with that. However, we have found developers are opinionated in that respect, and for instance assign `null` as the default value of all their inputs.

That is my reasoning for why the autocomplete works the way it does, but I'm happy to hear your thoughts.

(I was using the autocomplete in my examples; the dropdown works the same way)

**Comment by KoenCa** [comment]
Ok, I understand it works that way for the autocomplete. For the dropdown I would think it worked more like the normal select input, because I noticed this when I transformed some select inputs to dropdowns. These inputs are used to filter some data via a API endpoint and when the filter is `null` we don't pass it to the API call. `null` or `undefined` seem the most logical values to "reset" a filter. So if we want to use the dropdown with these filters we now have to use another "artificial" empty value to get some text to be shown in the input? Something like `'empty'`? Not a big fan of this to be honest.

Would it be possible that FormKit only uses one of `null` or `undefined` as an "empty" value? So that users have a way to "reset" something. For example: `undefined` becomes the only "empty" value, then users can use `null` to reset something.

**Comment by sashamilenkovic** [comment]
@KoenCa Yeah, your issue makes sense. I agree, having to use an arbitrary string like `empty` isn't ideal. Perhaps you could just use `false` in place of `null` as `false` is not considered an empty value.

Otherwise, here's a playground example I put together as a workaround to accept `null` as a valid value by using an input hook: https://formkit.link/9e1a815bb586e241ed778a40323236b8.

**Comment by KoenCa** [comment]
The problem is we have dropdown filters with 3 options with the values: `null`, `false` and `true`, so we can't use `false` as empty value for those. That input hook works, but have no idea how that `inputStd` prop really works. Looks a bit like magic to me and how sure can we be that this doesn't change in the future with an update?

**Comment by sashamilenkovic** [comment]
@KoenCa Ah, gotcha. As for the input hook, `inputStd` is just an internal prop we set for normalizing values between single and multiple dropdowns/autocompletes/taglist, etc, and is also used a way for filtering out values we don't want to consider, `null`, `undefined`, `""`. This prop is very unlikely to change, but I understand the concern.

Perhaps it would be worth marking this issue as an enhancement, and allowing users to provide a prop, say `empty-values`, where you could assign an array of values you don't want to be considered as valid option values. What do you think about that? Also open to feedback on the name of the prop, perhaps `empty-values` isn't the most clear.

**Comment by justin-schroeder** [comment]
Thinking a bit more on this im not sure if this is something we should "formally" support via a prop, vs informally with an adhoc plugin. The reason here is FormKit has a canonical concept of "empty":

https://github.com/formkit/formkit/blob/master/packages/utils/src/index.ts#L167-L184

This includes "null" as a non-value. Granted, in our specific case here this is wrapped in an array, but Im concerned that if we have official props that allow things like `null` as values then it would bloat the rest of the package where lots of code relies on knowing whether something is actually empty or not.

Perhaps @KoenCa we can work on making a better solution for your use case via plugin or some other kind of fix.

**Comment by KoenCa** [comment]
Ok, in that case I guess we will go with an empty value of our own like `'empty'` and handle that in the logic. To me that is the most obvious and simple solution instead of a plugin that uses more internal logic that isn't really wel documented.
