### ISSUE TITLE
Priority of initial values (of the same input) in a form

### ISSUE THREAD

**Issue by MattFromGer** [formkit/formkit#1090]
### Reproduction

https://formkit.link/8f823ff3f622d53e569225a66cea33b1

### Describe the bug

If I have multiple initial values on a form for the same input, the "root value" of the form will win. Shouldn't it be the value closest to the input? The highest priority should be the initial value on the input itself. Like the priority with CSS selectors? Form < Group < Input

The example is also my use case. Of course it will take the initial value of the input the second time, because the initial form value is only set once.

### Environment

• OS: [macOS]
• Browser [chrome]
• Version [1.4.x]

**Comment by sashamilenkovic** [comment]
@MattFromGer I'm just seeing the default playground example (just a text input) from the link you FormKit playground link you provided.

**Comment by MattFromGer** [comment]
> @MattFromGer I'm just seeing the default playground example (just a text input) from the link you FormKit playground link you provided.

Sorry, I forgot to shorten the URL. I updated the initial post

**Comment by justin-schroeder** [comment]
This seems counter intuitive at first — but it is working as intended. Actually in Vue Formulate (FormKit’s predecessor) we had it work the way you described and it was a huge issue for users. Most developers use the `value` prop to set the initial state of a given input when no value is used. For example, you might use `United States` on a registration form as the default value of a country selector if your audience was mostly US based.

However, when a form is repopulated, for example to edit the account details of the same form you want the top-down data to "win" vs the "local" value. This issue is accentuated when you want to encapsulate your form inputs (say into an "Address" component) and reuse it in multiple places, yes you want to have a sensible default on some inputs, but you also don’t want to prop-drill to reach the `value` prop on those sub-components.

If you have further questions about this we’d be happy to answer.

**Comment by MattFromGer** [comment]
Thank you for your answer. It probably makes sense to leave it as it is if most devs are confused otherwise. 

Funny thing is, that my use case is indeed the address. I have a delivery address and a billing address. I just pass the data of the backend in the form, check if they're equal and hide one address behind a checkbox. If the user clicks this checkbox to indicate the addresses are deviating, then in my case the new address inputs are populated with the same values. But I wanted to have blank values.

So my workaround right now is, to compare the addresses before passing it to the form. If they are equal, I remove one of the addresses out of the object and only then pass it to the form. Maybe not as straightforward, but a solution I can live with :)

**Comment by justin-schroeder** [comment]
Perhaps you could group your billing/non-billing addresses by wrapping them in a `<FormKit type="group" name="shipping_address">` and `<FormKit type="group" name="billing_address">` — or for one of them prefix the names of the inputs.

**Comment by MattFromGer** [comment]
Hm I don't quite understand.. Here's another [playground link](https://formkit.link/e5e70ddcac4332f90e316c5babdc1bc2) that makes it more clear I hope
