### ISSUE TITLE
Reactivity issues for nested objects

### ISSUE THREAD

**Issue by pop123123123** [formkit/formkit#112]
### Setup
formkit version : `1.0.0-beta.4`
I also tried with `1.0.0-beta.5-bd20073`, so without the lastests commits on `release/beta.5`

### Bug
I use schemas to generate my form, but have reactivity issues when using nested inputs (with groups or lists).

Changing any value from outside of formkit does not update the internal formkit model of the form.

Here is a minimal example of the issue (not my usecase, but same problem).
[FormKit Vue Playground link](https://formkit.link/b670542dd3e384f1a1a74a7fcf3bd0f5)
You can see that the model is changed, and is reactive enough to be displayed by vue, but the changes does not seem to propagate to the nested inputs.

Right now I only found one workaround, which is to trigger the complete ref refresh (shown in the playground).

Is there a recommended way to do what I am trying to ? Or is it just a bug ?

**Comment by justin-schroeder** [comment]
Thanks for the good report and playground! A couple things one this:

1. Reset functionality itself will be in beta.5 — it is currently in progress.
2. `v-modeling` is actually a relatively expensive operation, so we aren’t currently using deep observation, although we may change this to help improve the DX and just put a note in the docs about it. As you found a way to force this is to provide a new object to your `ref.value`. Instead of `JSON.stringify()` you could just spread your object.
3. Finally, let me mention core node manipulation. Get your form’s [core node](https://formkit.com/advanced/core#node) and directly input values. You can even traverse to the specific inputs you want to input. This is *by far* the fastest/most performant way to make mutations in FormKit as it avoids most of Vue’s reactivity system. No v-model required at all. Here is an example of that: https://formkit.link/f14c3fdf32dcf04ec95a45379a2b3800

I'm going to leave this open as a reminder to figure out how to improve the DX on deeply nested setters.

**Comment by justin-schroeder** [comment]
Ah, i bet you are correct. We do a fast comparison value === value as the values are cascading down and deeply linked objects may not be getting a fair shake to update. Fair enough — definitely worth looking into further.

**Comment by justin-schroeder** [comment]
@pop123123123 deep v-modeling now works! We used a custom watcher implementation to prevent the need for any deep cloning so we can keep the performance as good as possible, and it seems to be running well now. If you open your example in beta.7 (the `@next` tag on npm right now) the initial reset to zero works just fine:

https://formkit.link/1a5e73bf79ac8589a44c8b21a7ababa4
