### ISSUE TITLE
[Schema + Repeater] Autocomplete always triggers the focus of the first row

### ISSUE THREAD

**Issue by Tragio** [formkit/formkit#1121]
### Reproduction

https://formkit.link/f8fa3b9e835fb97d1de6575ae7d9cb31

### Describe the bug

When I click in other autocomplete it always triggers the focus of the first one. I also tried to define several `key` to see if something was wrong, and maybe I'm not 😅 

![CleanShot_2024-01-13_at_14 46 45](https://github.com/formkit/formkit/assets/5109593/9ac06524-cef4-4471-859d-0a5c19aa8bad)

Thank you for the incredible work!! 🚀 

### Environment

• OS: macOS
• Browser: Chrome
• Version: 120

**Comment by justin-schroeder** [comment]
the issue here is that your items inside the repeater should not have explicit ids (or if they do they need to still be unique somehow) otherwise you have duplicate ids on the same page which will lead to bugs.

**Comment by Tragio** [comment]
@justin-schroeder makes all the sense. I thought it used some internal `ref`. Hope to have a future eslint-formkit plugin to avoid these little stupid things eheh. Thank you very much, keep up the amazing work. 😄

**Comment by justin-schroeder** [comment]
@Tragio in 1.5 we’re going to start shipping "development" builds of FormKit (similar to how vue has dev/prod builds) which should allow us to have much better warnings and errors while youre in development to avoid things like this. Up until now we have avoided these kids of nice dev-only messages since they would bloat the package size. So hope is on the horizon.
