### ISSUE TITLE
Locale is reset to default when showing a hidden form

### ISSUE THREAD

**Issue by Finrod927** [formkit/formkit#1143]
### Reproduction

https://formkit.link/2b2022283c4d4e6558990f9838dcdc16

### Describe the bug

Hi FormKit!
In my application, all my forms are in modals, only shown when needed.
I wanted to use the new `changeLocale` from version 1.5 but I noticed my forms were never translated, they always keep the default locale.

I played a bit in the playground and manage to reproduce the issue when hiding/showing the form: https://formkit.link/2b2022283c4d4e6558990f9838dcdc16

Steps to reproduce:
1. Default locale is `en`, at startup, the form is in `en`
2. Set the locale to `fr`
3. Hide the form
4. Show the form

Expected result: the form is shown in `fr`
Actual result: the form is shown in `en` (default value)

I think FormKit should keep the changed locale and not using the default value when creating a new form.

Thanks for you work :)

### Environment

- OS: Windows 10
- Browser: Chrome 120 & Firefox 121
- Versions:
  - FormKit 1.5.1
  - Vue 3.3.11

**Comment by justin-schroeder** [comment]
Thank you for the good reproduction. The crux of the issue here is the nodes for the hidden form do not yet exist, when they do exist they pull from the rootConfig which `changeLocale` does not change (for unrelated complex reasons).

We should be able to fix this by moving the source of truth for the active locale to the `@formkit/i18n` package.

**Comment by smomapz** [comment]
This is not only happening with conditional rendering but also with internal navigation like in Nuxt or with vue-router. Once you leave the page and revisit, the nodes are repainted and reset to the default locale.
