### ISSUE TITLE
Using FormKit from a CDN

### ISSUE THREAD

**Issue by mdixon4** [formkit/formkit#115]
### Reproduction

https://gist.github.com/mdixon4/b6a4f50844660374f90186d43deef88e

### Describe the bug

When attempting to use formkit via CDN esm build, the error `Unknown input type "text"` is thrown.

It is not just text types, choosing a different type (e.g. `textarea` or even `form`) gives the same error (e.g. `Unknown input type "form"`)

A full stack trace is below:

```
Uncaught Error: Unknown input type "text" ("name")
    at v (+esm:7:1134)
    at ve (+esm:7:8634)
    at setup (+esm:7:6811)
    at callWithErrorHandling (vue.esm-browser.js:1682:22)
    at setupStatefulComponent (vue.esm-browser.js:8486:29)
    at setupComponent (vue.esm-browser.js:8442:11)
    at mountComponent (vue.esm-browser.js:6364:13)
    at processComponent (vue.esm-browser.js:6339:17)
    at patch (vue.esm-browser.js:5942:21)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.esm-browser.js:6479:21)
```

### Environment

• OS: Windows
• Browser: tested on edge and firefox
• Version: same behavior in 1.0.0-beta.4 and 1.0.0-beta.5-bd20073 (@next)

**Comment by justin-schroeder** [comment]
@mdixon4 this is a super annoying issue with browser-based ESMs right now. I'll do my best to explain since it can be a real gotchya in general:

Basically, what is going on is `@formkit/vue` requires `vue` — pretty self explanatory, but there are some places where id does things like `import { inject } from 'vue'`. In a build environment, your build tool knows to use the version of vue that is part of the project in `node_modules` (as long as it is within version constraints) — but when loading in the browser from an ESM how does it know how to resolve "vue"?

Well — they try to "guess" basically, but if they guess a version that is not the exact version of vue you are using in your project — then you have 2 instances of the Vue module. So in your case the `createApp()` you called was done on a different instance of the Vue module than `@formkit/vue` imported. So when it tries to use your plugin configuration (include inputs) it finds none, because the plugin was registered on a different module — thus you get errors like "Unknown input".

If you take a look at `@formkit/vue` ESM that JSDelivr created: https://cdn.jsdelivr.net/npm/@formkit/vue/+esm you'll find this line jammed into the minified code:

```
import{defineComponent as b,getCurrentInstance as g,watch as h,watchEffect as k,reactive as j,h as $,inject as S,provide as O,onUnmounted as x,ref as A,markRaw as C,computed as w,createTextVNode as V,resolveComponent as _}from"/npm/vue@3.2.31/+esm"
```

So there is the culprit — your code is loading a different version of vue than JSDeliver's version. Now here's where things get really crappy — JSDelivr's (or unpkg etc) version Vue as an +esm doesn't work because it doesn't know to use the browser-based version of vue 😔

There really seems to be no great way to do full esm's in the browser if they have `peerDependencies` — except for using an import map which is not supported in any browser except chrome. Fortunately [Guy Bedford wrote a polyfill](https://github.com/guybedford/es-module-shims) for import maps.

Here's your gist forked with a working version: 

https://gist.github.com/justin-schroeder/e7540c3bbc76526695d90b49f0c6c01e

Frankly — I'm not entirely sure how we can improve this 🤔 but open to suggestion. One thing we can definitely do is ship a browser-friendly version of FormKit minified into a single ESM, but that doesn't solve the peerDependency issue

**Comment by mdixon4** [comment]
Hi @justin-schroeder, thanks for taking the time to explain so clearly. I can see it's a tricky problem. The import map solution works well. ✅

I can't figure out how to make it work using esm.sh though. I get a 500 error with the second URL here, but not sure what's wrong. But anyway, that's outside the scope of this project - but I'd mention it here in case anyone comes along with a working esm.sh setup.

```
import { createApp, reactive } from 'https://esm.sh/vue@3/dist/vue.esm-browser.js'
// This URL gives a 500 error:
import { plugin, defaultConfig } from 'https://esm.sh/@formkit/vue?alias=vue:vue@3/dist/vue.esm-browser.js&deps=vue@3'
```

Thanks again for your help!

**Comment by justin-schroeder** [comment]
There's still not a great way to do ESM imports, but this gist can serve as a helpful guide for future explorers: https://gist.github.com/justin-schroeder/e7540c3bbc76526695d90b49f0c6c01e
