### ISSUE TITLE
validation-visibility blur is invalid

### ISSUE THREAD

**Issue by aegorx** [formkit/formkit#116]
### Reproduction

https://formkit.com/essentials/validation

### Describe the bug

```
<FormKit
  type="text"
  label="Phone"
  placeholder="xxx-xxx-xxxx"
  :validation="[['required'], ['matches', /^\d{3}-\d{3}-\d{4}$/]]"
  validation-visibility="blur"
  :validation-messages="{
    matches: 'Phone number must be formatted: xxx-xxx-xxxx',
  }"
/>
```

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
Hi @aegorx sorry im not following what youre issue is:

https://formkit.link/ebfc6229c206699d2e96163af595641b

blur seem to be working fine? Can you further specify your issue?

**Comment by aegorx** [comment]
Thank you for your reply.

It does work the first time, but once an error is triggered, it becomes  Dirty mode.

**Comment by justin-schroeder** [comment]
That is the intended behavior. Once the input has been blurred, we dont want to "hide" validation messages from the user again as this produces a very frustrating UX — where you have to play whack-a-mole with the validation errors in order to resolve your form. But if you think there is some kind of `validation-visibility` behavior missing feel free to open a new feature request issue with a detailed flow of the desired behavior.

Thanks!
