### ISSUE TITLE
Switch to peerDeps

### ISSUE THREAD

**Issue by hecktarzuli** [formkit/formkit#1160]
### Reproduction

http://no-preview.org

### Describe the bug

I was getting preview failures in my nuxt project.
`
[nuxt] [request error] [unhandled] [500] Cannot find module '/Users/joshdel/Documents/code/uwp-ssr-v3/.output/server/node_modules/vue/server-renderer/index.mjs' imported from /Users/joshdel/Documents/code/uwp-ssr-v3/.output/server/chunks/handlers/renderer.mjs
`
I noticed Formkit was using it's own version of Vue, vs Nuxt's version of Vue.
```
joshdel@LT-FRMACJOSHDEL uwp-ssr-v3 % yarn why vue
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "vue"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "vue@3.4.6"
info Has been hoisted to "vue"
info Reasons this module exists
   - Hoisted from "nuxt#vue"
   - Hoisted from "@vueuse#nuxt#nuxt#vue"
info Disk size without dependencies: "2.19MB"
info Disk size with unique dependencies: "8.24MB"
info Disk size with transitive dependencies: "17.43MB"
info Number of shared dependencies: 18
=> Found "@formkit/vue#vue@3.4.15"
info This module exists because "@formkit#nuxt#@formkit#vue" depends on it.
info Disk size without dependencies: "2.21MB"
info Disk size with unique dependencies: "8.25MB"
info Disk size with transitive dependencies: "17.45MB"
info Number of shared dependencies: 18
```
I noticed formkit/Vue has Vue as a normal dependency vs peer or dev dependency, can it be changed?  It seems most of your other packages are that way, and I would assume anyone using Formkit would first have to have Vue already installed.

After I updated my package.json to include
```
"resolutions": {
    "vue": "3.4.15"
  }
```
it fixed my issue with Nuxt, but I really shouldn't have to do this.

### Environment

Nuxt 3.9.0
Formkit 1.5.0

**Comment by justin-schroeder** [comment]
In theory they should resolve to the same version, but I’ve seen this happen too. We originally used to specify peerDependencies instead of dependencies but switched because it was leading to a different set of issues too 😂

That said — I 100% agree that semantically, strategically, spiritually, and emotionally these vue should be a peerDependency and related, @formkit/vue should be a peerDependency for @formkit/pro too. So in summary, we should probably make this change and fight the other issues that cropped up from using peerDeps instead of the ones that crop up using deps.
