### ISSUE TITLE
FormKitSummary header message not translated

### ISSUE THREAD

**Issue by SuddenDev** [formkit/formkit#1227]
### Reproduction

https://formkit.link/7739a8dc3d20ea8a0e812d044ab291cb

### Describe the bug

Currently there seems to be no option to change the header message of the FormKitSummary component. In my local repo, I'm using the @formkit/i18n  package as well, but that does not translate the header message either.
Is there any way? I was unable to find any documentation on this component.

Additionally another question: Is there a possibility to manually hide the summary? I did find out that you you can listen on the show Event and force it to be always visible, but no way to close it programmatically.

### Environment

• OS: macOS 14.1.2 (23B92)
• Browser: Chrome, Safari, Firefox
• Version: 1.5.5

**Comment by fenilli** [comment]
I will take a look at the translation of the header, but for closing it programmatically you can by doing a `v-if` on it.

**Comment by justin-schroeder** [comment]
The errors in the summary should use the same locale as the inputs: https://formkit.link/b043a507803521aa8d34183fabbbfb98

That said, the primary message "There were errors in your form." is not translated properly due to a bug in `changeLocale()`(#1143) — so I’ll close this in favor of resolving that issue.
