### ISSUE TITLE
Form inputs marked as invalid after touch when resetting form

### ISSUE THREAD

**Issue by angel200sdnot** [formkit/formkit#1376]
### Reproduction

https://formkit.link/4413cee2fb6db8dbde0ecc5d8203d41b

### Describe the bug

When i reset a form, the inputs will get marked as invalid after touching them even if the inputs have no validation

### Environment

• OS: Windows 10 Pro
• Browser chrome
• Version 1.6.3

**Comment by dominikklein** [comment]
Yes, I also saw some strange things related to the invalid state in our forms after clicking submit.

**Comment by andrew-boyd** [comment]
This is the change we made in `1.6.3` that affects the `data-invalid` prop — which is what the Regenesis theme relies on for showing invalid state stylings. 

https://github.com/formkit/formkit/commit/ec8b77acf1d86d01e5d7e470b047ae3de20f641a

The change was made because previously when an input was validating, it would toggle the invalid state and associated styles while validation was still pending. 

Likely something we’ve overlooked for consideration in the new computation. Thank you for the reports.

**Comment by justin-schroeder** [comment]
Fixed in 1.6.4
