### ISSUE TITLE
up/down/delete buttons not read properly by screenreader

### ISSUE THREAD

**Issue by LindaMeijering** [formkit/formkit#1379]
### Reproduction

https://formkit.link/1ec7860cf08f8ebd8a6c2dfc10b95720

### Describe the bug

It reads "button list item". If i go to the html to the span with Move down etc. and remove all the classes and put sr-only instead it works like it is supposed to.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by sashamilenkovic** [comment]
@LindaMeijering Just to be clear, did you mean to include the prop `draggable` on the repeater in your playground example? Or are you referring to another element?

**Comment by LindaMeijering** [comment]
@sashamilenkovic  My mistake, i mean the up down and delete buttons on the right side of the element. Not the draggable prop.

**Comment by sashamilenkovic** [comment]
@LindaMeijering This is another issue that seems fine when using the native screen reader (Apple Voiceover). If you inspect the element, you can see the span contains the inner text "Move Down". Not sure we want to make any sort of change just because this extension is not working properly (which is scheduled to be deprecated) :  https://chromewebstore.google.com/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en-US&utm_source=ext_sidebar,

**Comment by LindaMeijering** [comment]
@sashamilenkovic Microsoft narrator is indeed fine 👍

**Comment by LindaMeijering** [comment]
Same for this one, Microsoft narrator works well.
