### ISSUE TITLE
useSchema function should accept an Array of FormKitSchemaNodes as well.

### ISSUE THREAD

**Issue by kgierke** [formkit/formkit#141]
### Describe the feature

After trying to build my own Input Library I found two smaller issues/missing features:

First of all I think the `useSchema` function should accept an Array of `FormKitSchemaNodes` as well, since it can be possible to have more than one direct child schemes. Probably even better would be to change the `FormKitInputSchema` type to include `FormKitSchemaNode[]` as well.

Code i'm talking about: https://github.com/formkit/formkit/blob/master/packages/inputs/src/compose.ts#L115

Second thing: I think the `useSchema` function as well as the `localize` should be in an extra package to make it easier to use for people who want to build input libraries, as these two function are fairly common to be used. `localize` could probably also be a good fit for the `@formkit/utils` repo.

**Comment by justin-schroeder** [comment]
Thanks for the suggestion. I agree that we should come up with a way to accept an array of schema nodes for `useSchema` 👍

Is there a reason that `localize` should be moved to utils vs keeping it in inputs? FWIW it actually cannot be moved to utils because `@formkit/utils` is at the root of the whole dependency graph, and `localize` requires some typings from `@formkit/core` — so that would be circular. My hope is that the `inputs` package would _be_ that extra package you're describing, a self-contained project of inputs and utilities for building inputs.

**Comment by justin-schroeder** [comment]
Side note, I'd be really interested to hear your general feedback on building your own input library @kgierke. Feel free to [DM me in discord](https://discord.gg/NZ6nchBDGx) (justin-schroeder#2348)

**Comment by kgierke** [comment]
> Is there a reason that localize should be moved to utils vs keeping it in inputs?

No the reasoning was to only have one dependency for building libraries (@formkit/core) but I think using (@formkit/inputs) should also be fine.

I will drop you a message throughout the weekend on discord.

**Comment by justin-schroeder** [comment]
I actually think I've changed my mind on this — having a single root element allows us to provide simple extension capability via `extends()` — this would not be possible without a root node. That said, you can still use a "fragment" style node:

```js
{
  $el: null,
  children: [
    // add multiple here
  ]
}
```
