### ISSUE TITLE
Changing a value in the form programmatically doesn't reflect on text areas

### ISSUE THREAD

**Issue by abdelrahmansafwat** [formkit/formkit#1448]
### Reproduction

https://formkit.link/6aad13a0818834d6c87cf4a9ef5df7b2

### Describe the bug

If there's a form that uses a v-model, and you change one of the fields of the v-model programmatically, it doesn't reflect on the text area.
Example:
If the value of the text area field changes based on a change that happened in a dropdown field.

### Environment

• OS: Ubuntu 22.04
• Browser: Firefox
• Version 1.6.x (latest)

**Comment by arberk6** [comment]
this also happens with other types, such as text type

**Comment by justin-schroeder** [comment]
This is admittedly a bit confusing, but I can’t mark it as a bug since there is no path to solve it internally.  Let me explain a bit: the `@input` event is called *synchronously*, but Vue’s v-model doesnt update synchronously, it updates on a `queueMicrotask` — this means your event is being called — the v-model value ref value is updated in your callback, but before that value can be pushed back down into the form by Vue’s prop changing, another emit will be fired with the updated autocomplete value, ableit with the original textarea value. This is unfortunately just an artifact of having `3+n` data binding and relying on vue’s value to propagate back down — and one reason i often tell people to try and avoid using `v-model` for objects and instead use direct node manipulation (even in non-formkit vue, I'd recommend avoiding v-model when dealing with object data).

There are simple 2 solutions:

1. Wait for that `queueMicrotask` to run before making your change to the v-model object. this is easy enough to do with Vue’s `nextTick()`.

2. Directly get the node of input you want to modify and input it’s value. This is going to generally be the most reliable way to work with complex data as FormKit will ensure everything stays in sync internally. Here are examples of both:

https://formkit.link/b14856fb3fc1610e2039b402fe1bde7f
