### ISSUE TITLE
[BUG] SSR + v-model + local Storage

### ISSUE THREAD

**Issue by kevcomparadise** [formkit/formkit#1451]
### Reproduction

https://formkit-srr-pinia-reproduction.vercel.app/

### Describe the bug

Hello,

We are encountering a bug when trying to retrieve values previously saved in a Pinia store from the local storage (I know there is a LocalStorage module, but we need to use the data across multiple pages).

Upon refreshing the page and when I am in floating label mode, the state of the field is incorrect; it remains as data-empty=true.

Here is the reproduction repository.

### Environment

• OS: All
• Browser All
• Version N/A

**Comment by kevcomparadise** [comment]
Here repository : https://github.com/kevcomparadise/formkit-issue-1451

**Comment by kevcomparadise** [comment]
I have just tested this in the playground of the repo and the result is the same. This time, I didn't use Pinia but only VueUse with async storage. In the console, I get a "Mismatch hydration" error. The `data-empty` attribute remains `true` even after the data has been loaded from local storage.

**Comment by justin-schroeder** [comment]
Hmm. I think the issue here is the hydration *does* mismatch since the server rendered version does not have any of the values you provided immediately on load. I think there could be 2 work arounds:

1. Use something like `<ClientOnly>` to not server render.
2. Do not immediately hydrate the form using local storage. wait till the form has mounted and then use `formNode.input(localValues)` to re-hydrate the form.
