### ISSUE TITLE
Radio input with options do not emit 'change' event

### ISSUE THREAD

**Issue by leewes** [formkit/formkit#1508]
### Reproduction

https://formkit.link/b501a35763029043fbeeaf8ecee81e68

### Describe the bug

Passing an `options` prop to `radio` inputs do not emit a change event. However, radios with one option without using `options` will work as expected: https://formkit.link/8ca5d36c11e8ff76ab55cbe49a77130e

### Environment

• OS: macOS Sequoia (Version 15)
• Browser: Chrome
• Version: 129.0.6668.71

**Comment by justin-schroeder** [comment]
`change` is not a formkit event (for lots of reasons, but most specifically performance). The DOM does have a change event however so normally when use use `@change` that attribute falls through to the input and you just get the normal change event. Radios technically have a change event in the DOM, although its not very useful since each individual radio emits its change. We dont plan to support an explicit change event, but instead you can use the @input event to receive updates for the entire node.
