### ISSUE TITLE
FormKitSchema: empty data and no submit-event

### ISSUE THREAD

**Issue by fabianwohlfart** [formkit/formkit#1544]
### Reproduction

https://formkit.link/7e511ade806581ff444923f7fff227db

### Describe the bug

I generated a schema with the Kickstarter, the playground was automatically generated from this.
On the playground I cannot get two things to work: (a) display the entered data, (b) submit the form.

### Environment

Formkit 1.6

**Comment by andrew-boyd** [comment]
Hey there! I think there's a bit of a misunderstanding about what the `data` object for schema is. The `data` object is a way to provide values (including functions) to your schema so that they can be referenced while still keeping the schema serializable for storage in a database.

Here's two ways to handle form submission and showing the form values.

If you want a full schema solution: 
https://formkit.link/a64ab97d9fa433f5589986dcce5e9ce6

Alternatively, you can move your `form` to the template and nest only the input schema inside of it. Allowing you to use the `@submit` property and destructure the form values from the default slot:
https://formkit.link/a6dc66c5056bb8e24e54463fc47f6e28

**Comment by fabianwohlfart** [comment]
Hi Andrew, thanks for the quick reply and the examples! That indeed helped a lot. I wish I found these in the docs.

My big confusion was the usage in Nuxt, where the provided code does work. Compare it to this issue https://github.com/formkit/formkit/issues/1511 – therefor I was searching for solutions, but could not find any, and was misusing the data object.
