### ISSUE TITLE
Maximum recursive updates exceeded when set the value after fetched.

### ISSUE THREAD

**Issue by TheXiong** [formkit/formkit#1565]
### Reproduction

https://stackblitz.com/edit/vitejs-vite-wttduc?file=src%2FApp.vue

### Describe the bug

![image](https://github.com/user-attachments/assets/61afdcd4-3b80-418a-887e-6e8d77d08a8c)
**when I set value prop to schema and set value after 2 seconds, this error will show.**
_Uncaught (in promise) Maximum recursive updates exceeded. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function._

### Environment

• OS: [e.g. iOS] windows7
• Browser [e.g. chrome, safari] chrome
• Version [e.g. 22] 1.6.7

**Comment by justin-schroeder** [comment]
This is close — but it looks to me like it needs to be made into a dynamic list instead of a standard one since you are deriving the value of the input recursively (the value comes from columns/rows, which in turn come from the value).

https://stackblitz.com/edit/vitejs-vite-s2vexd?file=src%2Ftable.js
