### ISSUE TITLE
Checkbox validation with "required" works only the first time

### ISSUE THREAD

**Issue by dominikklein** [formkit/formkit#169]
### Reproduction

https://formkit.link/f95a4040044675d4f8712c48bed94ffe

### Describe the bug

When you use `required` on a checkbox it's only working when you didn't checked the checkbox before. After it was checked and unchecked the required validation is not complaining.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
Ok — this is super nuanced, but technically this is working as desired (we can then further discuss if it makes any sense) — a checkbox that has been checked and unchecked has its value set to `false` (by default you can change this with the `on-value` and `off-value` props).

However, `false` is a valid input indication so it passes the required check because it does have a valid value. If you want to check if a given checkbox has actually been checked you can leverage the `accepted` rule (https://formkit.link/e97ef74c02659403554449d194ab6def).

Now on the surface that is pretty confusing, so I'm not sure what the right path forward is here. I feel making `false` an empty value is not the right path forward, because then false could never fulfill the `required` rule and certainly it should sometimes.

**Comment by GustavoFenilli** [comment]
I think the only problem with the current behaviour is that the value is not set to false by default, so to send a false value to the `required` rule you need to check and uncheck the box, that is odd because I can totally see a user saying:
> if the first time I tried and the uncheck didn't work, why does it work the second time? 

And if the behaviour for sending false values is meant to be it should be setted to false by default, otherwise it does not make sense that required rule let it pass a false value.

**Comment by dominikklein** [comment]
Yes, again a difficult question and I think there are different expectations in the usage. I was only wondering, but now I'm also not sure what's the best.

**Comment by justin-schroeder** [comment]
In general the approach to inputs has been "dont set a value until it is specified". So the default value all inputs is basically "undefined" unless otherwise noted. The only real exceptions to this are array-only values like multi-select and multi-checkbox, or repeater (not available yet). Those automatically change their empty default value to an empty array:

https://formkit.link/44b24fc9e336387b56b1a2d48b8c2379

So, as @GustavoFenilli is suggesting we could make another exception and set the default of an empty checkbox to the `off-value`.

That said — perhaps the most confusing thing is how the rule itself works because of the "lexical" nature of the rule. I think developers hear "Checkbox is required" in their mind when they type `<FormKit type="checkbox" validation="required" />` — so it might be an improvement to make the default value the `off-value` but I think people will likely keep getting tripped up on this 🤔

**Comment by GustavoFenilli** [comment]
I think changing the default to starting at the `off-value` and changing the default behaviour of `required` to need the `on-value` to be set, would make more sense, as if the person needs to send the both `off-value` and `on-value` he wouldn't add the `required` validation.

**Comment by dominikklein** [comment]
Sounds for me also like the best solution.

**Comment by guyinpv** [comment]
I'm seeing a similar odd behavior even with the `accepted` validation, not just `required`.

If I have a fresh form that the user hasn't touched, they can immediately submit it and the `accepted` validation doesn't even trigger. This hardly works for the intended purpose of things like "accept the terms" since the user can submit strait away without accepting them!

But if the user first checks the box, then unchecks it again, the error will begin to trigger the `accepted` validation.

The only way I can make it works right is using both `required|accepted`. Required will catch that first submit attempt if they haven't touched the checkbox at all, and accepted will catch others after that.

The documentation states: "The value must be yes, on, 1 or true. Useful for checkbox inputs — often where you need to validate if someone has accepted terms."
This ends up being misleading since it doesn't actually trigger unless the user first interacts with the checkbox or has `required` on as well.

I guess I'm just saying, `accepted`, should implicitly assume `required`, or at least make this known in the docs as a caveat.

This can be tested easily in the playground, just put a checkbox there with accepted as the validation and `validation-visibility="live"`. The error won't show up until you check/uncheck the box. Then add "required|accepted" and you'll see the initial message says "is required" but if you check/uncheck it now says "please accept..." because it switched rules after interacting.

**Comment by wvffle** [comment]
> The only way I can make it works right is using both required|accepted.

Thanks @guyinpv, I tried `accepted|required` but it didn't work for me

**Comment by justin-schroeder** [comment]
Perhaps a good solution here would be to change the `accepted` rule to have `skipEmpty` set to `false`. You can actually do this yourself by importing it and re-assigning it in the config (see example), but we could also do this by default.

https://formkit.link/79fa0a8683df23f40762941a9e851f6b

**Comment by justin-schroeder** [comment]
Also worth mentioning you could use a [rule hint](https://formkit.com/essentials/validation#rule-hints) to do this inline:

https://formkit.link/bf8115f77a6ec461825eaf8284a4cc62

**Comment by guyinpv** [comment]
> Also worth mentioning you could use a [rule hint](https://formkit.com/essentials/validation#rule-hints) to do this inline:

This works and is easiest to implement quickly. I still think greenhorns will fall into the same trap as me and assume the 'accepted' filter will automatically prevent the blank submission. It's not intuitive to think it wouldn't, especially since the docs say it only passes for "yes, on, 1, or true". Maybe add "also blank but only if they don't check and uncheck it first".

The docs do say that only 'required' works on empty fields, but it certainly feels to me like 'accepted' should too. At least in the context of a single checkbox. Not sure how it works for a grouping.
