### ISSUE TITLE
Add `$at` to schema for node traversal.

### ISSUE THREAD

**Issue by fenilli** [formkit/formkit#193]
### Describe the feature

Adding the traversal nodes to the schema using `$at` and adding their tokens aswell so `$parent` and `$root`, this would make getting parent values easier for schema based components.

**Comment by justin-schroeder** [comment]
@GustavoFenilli do you think this is still relevant?

**Comment by GustavoFenilli** [comment]
It might be, but not sure that many people would use it as you could do `$get(node).at` but the `$root` and `$parent` might be useful to be able to pass, as how would you get the parent value from an schema?

**Comment by justin-schroeder** [comment]
You should be able to just get the node directly:

https://formkit.link/e9ca9cfa42e397b419eb736e4c8f52e3

This is because each `$formkit` destructures its `context` object into each `children` context.

**Comment by GustavoFenilli** [comment]
I meant how would you get the parent from a child?

Also it looks like  `$get(node).at()` does not work I believe, it gives `$at` is not a function.
https://formkit.link/3302c400d66eed4acc8a45c928eee697

**Comment by justin-schroeder** [comment]
its not a perfect system, but you can also do something like: https://formkit.link/d867cbb6dcccbb8ed99f087dc11b5aa7

perhaps we do need something like `$at`. `$parent` is irrelevant, because `$node` is always the `$parent` (because of the destructure). This would work to traverse `$node.at(text2)` except that would only run one time on initialization, so if the input you are trying to access mounts after the one you are referencing you will not have access. I'm not sure there is a great solution to this though, since a reactive `$at` would probably be really expensive as it would need to be constantly be attempting to traverse to a given path just to see if the node is there. By contrast, `$get` listens to the global registry to determine when a node is mounted, since nodes with `id` are automatically mounted.

Maybe we could "fake" a reactive traversal by determining the absolute address of the desired node, and then when each node mounts emit its address as a bubbling event. The root node could be notified of the mounting node and in turn call the listeners of the child nodes that are "expecting" a node to mount at the given address.

Phew — I think that would be possible although not particularly fun haha.
