### ISSUE TITLE
Importing inside formkit.config.js breaks playground

### ISSUE THREAD

**Issue by GustavoFenilli** [formkit/formkit#202]
### Reproduction

https://formkit.link/059ed92473960c7d1580de17c1287f0b

### Describe the bug

When you try to import inside the formkit.config.js file, it breaks the playground with module not found.

### Environment

• OS: Windows
• Browser Chrome

**Comment by andrew-boyd** [comment]
@GustavoFenilli - so there's as lot going on with how we have to parse the raw files and build them inside an iFrame to get the Vue3 code examples to work on our Nuxt 2 documentation site. I believe what's going on here is that the `.vue` components are being loaded as components into the Vue instance for the playground, but they are _not_ a part of the import map — we're able to fake it inside of `.vue` files for you but a `.js` file such as the FormKit config doesn't have a way to resolve the `.vue` path.

I do think there's a workaround though. You can import from `vue` because we're doing our best to enforce a shared instance and then define an async component to a variable. This will then pull the same component from the internal module cache we have on the Vue side of thing. 

Does this get you further along? https://formkit.link/4f4b4b98bcb51031ded0ba97422d0398

**Comment by GustavoFenilli** [comment]
Good work around, it works to not break the playground itself, but when trying to add as an input to formkit it also does not work.
https://formkit.link/876555d70c15647137e45e5b40d0a5bd

**Comment by GustavoFenilli** [comment]
If it works, it works!

**Comment by andrew-boyd** [comment]
Perhaps in the future I can sniff out `.vue` import statements in the `.js` files and rewrite them if they're local files to be variables. So:
```
import test from `./test.vue`
```
Becomes:
```
const Test = window.moduleCache['test.vue']
```
in the internals of the editor.

**Comment by GustavoFenilli** [comment]
Something like compiler transforms? if it detects x code, transform it to y.

**Comment by andrew-boyd** [comment]
That's right. It's pretty much what we're doing already. We load the editor contents as raw text files and splice them into a `srcdoc` for the iframe vue. Because we need to run Vue 3 examples in a Vue 2 codebase.

**Comment by andrew-boyd** [comment]
@GustavoFenilli - the restructure needs more time in the oven. Had to revert for now due to unintended side-effects across the docs site. I'll re-open this issue.

**Comment by justin-schroeder** [comment]
@andrew-boyd is this still a planned update?

**Comment by andrew-boyd** [comment]
This one feels like it would have some value. I'll need to re-acquaint myself with what was going off the rails back in April.

**Comment by andrew-boyd** [comment]
There is a solution in place for this now!
