### ISSUE TITLE
Non-schema to schema conversion/docs

### ISSUE THREAD

**Issue by totalhack** [formkit/formkit#208]
This is maybe part feature request, part documentation request.

I am hoping to use formkit for an upcoming project and will be exclusively using the schema based approach since it fits my use case. I've read the schema documentation, but many examples do not use that approach and the schema docs don't seem to cover translating every scenario from non-schema to schema. So I have a few questions:

1. Is there a tool or function to export a JSON schema from a non-schema based example?
2. Is there documentation that maps all non-schema parameters to schema parameters? For example, the [starter app](https://github.com/formkit/formkit-vue-starter-project/blob/master/src/App.vue) uses `validation-behavior`, which I could not find documented, so I assumed it would map to `validationBehavior` when used with the schema approach based on seeing camel case used in another schema example.  EDIT: I see in the changelog this changed to validation-visibility, but still wondering if the only rule is "convert it to camel case" and it all *should be supported.
3. Is `v-model` supported in the schema? See [this line in the starter app](https://github.com/formkit/formkit-vue-starter-project/blob/master/src/App.vue#L29). I can replicate this behavior by not having a dedicated `recommendation` field and instead putting it right in `formData` and passing that as the `:data` param to `FormKitSchema`, but I was just wondering if schema supports `v-model` since `vModel` didn't seem to work. Unclear if this would ever be strictly necessary, but sticking with the theme of trying to replicate non-schema to schema.
4. I seem to be able to pass whatever I want for both param names and param values without formkit complaining. For example, a typo like `validationVisibility: "love"` gets through without any complaints. Any plans to change this to help dx?

Thanks.

**Comment by GustavoFenilli** [comment]
1. I don't think there is one at the moment.
2. The schema documentation may be lacking some information on how to do everything using it ( one of my ideas was to add both option and composition for every example, maybe adding the shema ones too would be cool ), but the validation-visibility is here https://formkit.com/advanced/schema#formkit-inputs.
3. I don't think v-model would be supported, as the schema is mostly meant to be framework agnostic, and v-model is vue exclusive.
4. You're right, I think props should have a validation check for values to help DX, and a default value to fall if passed a wrong value.

**Comment by justin-schroeder** [comment]
You can v-model, but you need to provide the v-model via an outer wrapper. v-model is a vue template feature only.

**Comment by justin-schroeder** [comment]
Here's my stab at your questions @totalhack:

> 1. Is there a tool or function to export a JSON schema from a non-schema based example?
- No there is not. This would be really cool — but also incredibly difficult — nearly impossible — to build.
> 2. Is there documentation that maps all non-schema parameters to schema parameters? For example, the [starter app](https://github.com/formkit/formkit-vue-starter-project/blob/master/src/App.vue) uses `validation-behavior`, which I could not find documented, so I assumed it would map to `validationBehavior` when used with the schema approach based on seeing camel case used in another schema example.  EDIT: I see in the changelog this changed to validation-visibility, but still wondering if the only rule is "convert it to camel case" and it all *should be supported.
- Sorry about that — sounds like we need to update the starter app as validationBehavior was deprecated some time ago in favor of `validationVisibility` — and yes, the rule is convert it to camel case. This is really a piece of vue functionality rather than FormKit — it expects props in kebab case and wants them used internally as camel case — we try to follow suit.
> 3. Is `v-model` supported in the schema? See [this line in the starter app](https://github.com/formkit/formkit-vue-starter-project/blob/master/src/App.vue#L29). I can replicate this behavior by not having a dedicated `recommendation` field and instead putting it right in `formData` and passing that as the `:data` param to `FormKitSchema`, but I was just wondering if schema supports `v-model` since `vModel` didn't seem to work. Unclear if this would ever be strictly necessary, but sticking with the theme of trying to replicate non-schema to schema.
-Yes v-model is supported, but you need to "write" your v-model "outside" the schema. Since FormKit can v-model to any depth you can still use it in this way. That said, v-model is not the preferred way to read/write values to inputs in FormKit (totally acceptable, just not preferred) — the most efficient way is using `node.input()`.
> 4. I seem to be able to pass whatever I want for both param names and param values without formkit complaining. For example, a typo like `validationVisibility: "love"` gets through without any complaints. Any plans to change this to help dx?
- Validation on the props would be nice...im torn about whether to do this or not though. Prop validation is a runtime behavior that needs to ship to everyone's browsers even when they are using the props the correct way. We have a lot of props, which means a lot of validation rules, which means a lot of bytes shipped to a lot of browsers unnecessarily. Alternatively, TypeScript can do this validation for you and build time and shave those bytes off.

Feel free to jump into discord if you have more questions! We'd be happy to chat there.

**Comment by totalhack** [comment]
Thanks @justin-schroeder. 

I had assumed maybe you guys were powering everything with something that matched the JSON schema under the hood and the components were just a layer above that. If not, I can see why that translation would be difficult. 

Regarding prop validation, that's a good point and a tough call. Relying on TypeScript to do it is probably fine for many cases -- maybe you guys could adjust and maintain the starter app to support this. Perhaps some additions to the documentation would help too. The current docs are well-written but an "API Reference" section that just lists the components and their supported props/settings would be helpful (apologies if I've missed it).

I hope you don't mind me asking these questions here first. Discord is a bit of a black hole for those searching Google or perusing the Github repo, so I like to start here for others' sake. I'll jump in there if I have further questions though!

**Comment by justin-schroeder** [comment]
@totalhack everything under the hood is powered by schema actually 🪄 but unfortunately going from vue templates to formkit schema is very hard because the schema is a subset of the template, so some template features would need to be re-written or removed. A bit like going from JavaScript to TypeScript — its pretty hard to do. It would be easier, actually to have tool that showed the equivalent template code of a given chunk of schema.
