### ISSUE TITLE
Add functions to clear errors on specific inputs — including auto-clearing

### ISSUE THREAD

**Issue by J87NL** [formkit/formkit#211]
### Reproduction

https://formkit.link/52a71225db2d0e9872f93c7d0301bcd5

### Describe the bug

I'm using `:input-errors="errors"` to display any errors that are returned by my Laravel FormRequest validation.

If there are multiple validation errors and you fix one of them, but leave another incorrect, the error message of the corrected input is expected to be cleared. As shown in the simplified reproduction-example above after the second and third the error messages for all inputs remain visible.

I hope this can be fixed, or maybe I'm doing something wrong? Thanks for the amazing package!

### Environment

• OS: Ubuntu
• Browser Chrome & Firefox
• Version 100.0.4896.127 / 99.0

**Comment by justin-schroeder** [comment]
@J87NL Currently `input-errors` (as well as `setErrors()` — which you might prefer actually) are made to allow a user to "layer" mutliple calls setting errors on different inputs — so to clear the errors on a given input you need to provide its key and pass it an empty array indicating you want to set it back to empty.

https://formkit.link/ec527a7aa09872ad8ef9d2dd513f12fe

That said — we need additional/better ways to clear errors, so I'm going to turn this bug report into a feature request :)

**Comment by GustavoFenilli** [comment]
Because most of the times backend validation errors do not return an empty array when there isn't an error, you could just reset before every submit all fields: https://formkit.link/cb26d526aa11f6ee436dda0014b895ae

But because we sometimes do not know all fields before hand ( maybe a builder ), and to get that would be a hasle, and to make it easier to use, I think `node.setErrors([], [])` should reset all fields, if I'm passing an empty array I don't have errors, instead of needing to specify every single input.
