### ISSUE TITLE
Node value not updated when `v-model`ed to undefined `ref`

### ISSUE THREAD

**Issue by huzaifahj** [formkit/formkit#235]
### Reproduction

https://formkit.link/ff5ee0658d2cf7d576feef57a014f524

### Describe the bug

The `deepChild` variable should be equal to the `deepChild` form input

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by GustavoFenilli** [comment]
I think it has nothing to do with children, but passing undefined to `ref()` and passing it to `v-model`.
https://formkit.link/0057e285c6504e425d6f49af14a3cb36

**Comment by justin-schroeder** [comment]
Yeah unfortunately this one will likely not be addressed. If the ref used to v-model is undefined FormKit is unable to determine that a v-model was actually there, and for performance reasons discards the v-model. This is an intentional optimization that is unlikely to change.

The good news, is literally any other empty-like value is acceptable, `null`, `false`, `0`, `[]`, `{}`, `""` — but if the `modelValue` prop is initially set to `undefined` it will not v-model.

**Comment by justin-schroeder** [comment]
In a very exciting turn of events @LinusBorg reached out on discord with a brilliant solution to this problem:

```js
const vm = getCurrentInstance()
const usesVModel = () => 'modelValue' in vm.vnode.props
```

Essentially checking the virtual node for the *actual* presence of `modelValue`. This differs from `modelValue in props` because that will add all props as `undefined` that are not specified by the user, but looking at the v-node gives us more internal data. This is going to ship in `beta.13` — great DX improvement.

Thank you @LinusBorg 🙏!

**Comment by huzaifahj** [comment]
Beautiful solution

**Comment by LinusBorg** [comment]
Happy to help out ✌️
