### ISSUE TITLE
Add prop checked to checkbox

### ISSUE THREAD

**Issue by GustavoFenilli** [formkit/formkit#237]
### Describe the feature

When creating something on the lines of a list of checkboxes, you need to check if the checkbox is checked or not at initial setup.

The way to do it now is to make sure `value` and the `on-value` are the same, but that gets quite cumbersome and verbose: `:value="rows.includes(material.id) ? material.id : false" :on-value="material.id"`.

It would also makes sense to just " get me the on or off value with a boolean approach ": `:checked="rows.includes(material.id)" :on-value="material.id"`.

**Comment by justin-schroeder** [comment]
this being a list of individual options?

**Comment by justin-schroeder** [comment]
Maybe you could provide a reproduction of how it sucks to do it so we can work out a better api

**Comment by GustavoFenilli** [comment]
Think about a table that has many checkboxes ( select a row of it )
https://formkit.link/8b6b4dd962955d5c1c08c7680a0ae06d

Or is there something I'm missing that could make this easier.

**Comment by justin-schroeder** [comment]
I'm concerned about the API confusion this could cause. I agree that making "checked" just work would be an improved DX, however there are more questions we need to hash out:

1. Is `:checked` reactive or only the initial value
2. What if someone has `:checked` and `:value` specified the rules will compete. How about `:checked`, `:value`, and `v-model`?
3. If we implement value and checked, will users be confused that those attributes do not operate the same as native checkboxes where "value" is the `on-value` of the input and `checked` is the enabled state (boolean)?

The intended use (without the `checked` feature) is to be able to set your entire form state from the parent input, like the `form` and all the children are hydrated appropriately. Perhaps the ":value" prop on a checkbox should only accept a boolean that operates like `checked` since we have `on-value` and `off-value`.

**Comment by draganescu** [comment]
👋🏻 Just wanted to chime in to say that the way to get the checkbox to be checked should be more proeminently documented as it is not directly evident that one should set `on-value` and `value` to same value. [Here](https://formkit.com/inputs/checkbox) there should be a section to specify this 😁 

Thank you!

**Comment by GustavoFenilli** [comment]
> The intended use (without the checked feature) is to be able to set your entire form state from the parent input, like the form and all the children are hydrated appropriately. Perhaps the ":value" prop on a checkbox should only accept a boolean that operates like checked since we have on-value and off-value.

I think this could solve the problem, but people using for other inputs may find it strange that they work differently.

1. Yes it should be reactive.
2. If someone has `:checked`, `:value` should be disabled I believe so it does not have competing rules, about `v-model` it should work the same as `:values` and `v-model` already work, but with `:checked` instead.
3. That may be the case, but it would be compatible with the current API, for this we could write at the documentation level explaining, as `:checked` works as a more native API.

But it may be easier indeed to just write at the documentation level that checkboxes `:value` os the same as the native `checked`, it does improve DX a lot, conforms with the native specs and it does not generate confusion about how it works.
