### ISSUE TITLE
Handling A Repeated Form

### ISSUE THREAD

**Issue by totalhack** [formkit/formkit#252]
### Describe the feature

In digging through the formkit code while analyzing [this](https://github.com/formkit/formkit/issues/251) issue I noticed that nodes are scoped globally in the `registry`. Let's say I had a page where I wanted to reuse a schema-based form definition to show the form at the top and again somewhere further down the page. It seems like the global registry (and use of getNode) would not support this unless I modified the IDs of each node in any additional instances of the form. But that's not very practical when trying to reuse a form definition. 

This would be a breaking change, but perhaps the global registry should be scoped to the form id/instance? Alternatively, maybe some feature to add a prefix to the node IDs when initializing the root node would be useful.

Thanks.

**Comment by justin-schroeder** [comment]
The global registry would not support that. You can add prefixes to your ids if you choose, or make them dynamic. You can also use other utilities to get the node other than id like the node event or by traversing to any node from any other node by using name-based dot notation paths or arrays (`node.at('location.street.city')`).

It's unlikely that we'll change the way the registry is scoped, but I'm open to other utilities that help access nodes more conveniently.

**Comment by justin-schroeder** [comment]
you only overwrite the global registry if you use and `id` twice. We chose this attribute because it is already globally unique to the DOM. For example, `getElementById` uses a hashmap to reference DOM noes, and we are effectively doing the same thing.

The point about `getNode` is that it is not the only way to get the nodes just like `getElementById` is not the only way to get an `Element`. It just happens to be the globally unique method of doing so.

If you do want to go down the path you're suggesting of giving ever node a unique id (again, not totally necessary, but also totally fine to do if you want) you can do that fairly simply with an expression:

https://formkit.link/84e3ff2c7c002a5ab92fe9b41a82573e

**Comment by justin-schroeder** [comment]
👍
