### ISSUE TITLE
Input event listener triggered immediately in beta.8

### ISSUE THREAD

**Issue by Jannick94** [formkit/formkit#267]
### Reproduction

https://formkit.link/8faacf65e3f164823a824ea6a6d4a84f

### Issue with @input listener being fired immediately in beta.8
When you open the developer console with beta.8 you will see `x` being logged immediately. When you switch to beta.6, this doesn't happen, the `x` gets logged when the actual input event gets triggered, which is the expected behavior.

### Environment

• OS: Linux
• Browser: Chromium
• Version: Chromium Version 100.0.4896.127 (Official Build) Arch Linux (64-bit)

**Comment by justin-schroeder** [comment]
This is accurate, but not a bug. The `@input` event changed between the two — `@input` is now debounced and does fire on init. It should not be used as a 1-1 of someone typing — the input is event is fired on a 20ms debounce of `node.on('commit')` — this occurs on initial hydration (what you are observing) and all other `node.input()` events.

In beta 6 and earlier the input event was not fired during the initial hydration — we deemed this to be a bug which is why you now have it emitted on startup. If its causing issues for you, feel free to reach out about those so we can formulate a good solution!

**Comment by Jannick94** [comment]
Alright, thanks for the quick response! I am however wondering how I would implement listening to someone typing in the field, without it obviously triggering on load aswell, I've tried `@input-raw` and `@update:model-value`, but both seem to behave the same as just `@input`.

**Comment by justin-schroeder** [comment]
@Jannick94 what kind of side effect are you hoping to apply?

**Comment by Jannick94** [comment]
For example: fetching from an API endpoint with the value entered by the user, (the API call should be debounced of course), but I don't want to do an API call on load without the user interacting with the input.

**Comment by Jannick94** [comment]
Another example where this might be useful:

I've created a custom select input to add a default disabled option for each select:

```
// InputSelectFormkit.vue
<select
    :value="context._value"
    :class="context.classes.input"
    @change="handleChange($event)"
>
    <option value="" disabled>Choose something</option>
    <component :is="context.slots.default"></component>
</select>
```

However, we also have some selects with specific values which are reused through our system, so I made another component which is based on the custom select component:

```
// InputFranchiseFormkit.vue
<form-kit type="select">
    <option value="1">Stichting verloning</option>
    <option value="2">Bouwverlonen</option>
    <option value="3">Sportverloning</option>
    <option value="4">Evenementverloning</option>
    <option value="5">Zorgverloning</option>
    <option value="13">Verloning.nl</option>
    <option value="14">Freelanceverloning</option>
    <option value="15">Mediaverloning</option>
    <option value="16">Verloningdev</option>
    <option value="17">Prae Artiestenverloning</option>
</form-kit>
```

The problem I'm now running into is that v-model on this component doesn't seem to be working:

```
Franchise: {{ form.franchise }} // stays empty
<form-kit
    label="Franchise"
    type="franchise"
    v-model="form.franchise"
></form-kit>
```

Maybe I'm missing some values that I need to bind manually? My expectation was that with the fallthrough attributes of Vue this would be working out of the box. I've also tried binding various events to the component above and updating the value with `context.node.input()`, but then I'm back at the problem these events are fired on load.

**Comment by justin-schroeder** [comment]
I'm not totally sure I understand the `type="franchise"` one — are you using a FormKit type="select" inside an input? If so that likely wont work because you would have an input node inside an input node. Probably not what you wanted to create, but its hard to tell from the existing examples. Perhaps a reproduction here could help narrow this down some.
