### ISSUE TITLE
The default button from the form component should have a type of submit instead of button.

### ISSUE THREAD

**Issue by StefanGhiban** [formkit/formkit#275]
### Describe the feature

I have used a form component to create some forms and I have realised that the default button from the form is of type button instead of submit. I have also implemented a plugin that adds a spinning gif while the form is loading in a tailwindcss form. In that plugin I search for submit inputs, but I cant find those buttons from the forms because they have the type button.

**Comment by justin-schroeder** [comment]
The default button is type submit. Can you provide a reproduction in the playground of your issue?

it’s possible your plugin doesn’t find the button because buttons have `ignore=true` by default to prevent their empty data from being added to the form data, but this prevents plugin inheritance too.

**Comment by StefanGhiban** [comment]
> The default button is type submit. Can you provide a reproduction in the playground of your issue?
> 
> it’s possible your plugin doesn’t find the button because buttons have `ignore=true` by default to prevent their empty data from being added to the form data, but this prevents plugin inheritance too.

I have looked into my problem again and now the button is of type submit. I might have read something wrong. Thanks for the help.
