### ISSUE TITLE
Clearing errors from the input-errors prop not working

### ISSUE THREAD

**Issue by Hepi420** [formkit/formkit#277]
### Reproduction

https://formkit.link/67cafcb5a106b7ab7422bbbc3dbc1e12

### Describe the bug

I set the errors from the backend with the input-errors prop and on the second submission after resubmission without the errors I replace the error object with an empty object(or with different errors) to clear the errors and it doesnt update on the form.

### Environment

• OS: [e.g. iOS] Windows
• Browser [e.g. chrome, safari] Chrome
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
So a couple things:

1. You dont need to `v-model` each input in FormKit. FormKit automatically collects all the input's values at the form level. However, just be sure to v-model a `ref` instead of a `reactive` object, or a sub-property of a reactive object. The way you are doing it isnt "wrong", its just something FormKit is already doing for you.
2. You found a bug! We're working through this now. Thanks for the submission.
