### ISSUE TITLE
@input triggers without user interaction and inconsistently 

### ISSUE THREAD

**Issue by leprincehector** [formkit/formkit#295]
### Reproduction

https://formkit.link/fdd44b1f28f454652135867bc1373b03

### Describe the bug

@input triggers without user interaction on the first input of the form but not on the second. 
See the formKit.link above and see the console.

As explained in issue #267 this is a problem when we want to edit data coming from the database, and we want to take some action when one of the input is modified by the user.  If @input fires without interaction and @change is not supported (as explained in issue #294) then there is no easy way to track the user interaction on the input element that fires @input without interaction.

What is more estrange:  If we take out the FormKit input 3 from the reproduction example, then the @input from input 2 stops firing.

Finally, I provided an additional <input type="text" on the example to show that it does not fire @input without interaction, and I think, IMHO, this should be the expected behaviour for FormKit inputs.

### Environment

• OS: MacOS
• Browser: chrome & safari]
• FormKit Version: Beta 8 & 9

**Comment by GustavoFenilli** [comment]
I think for your case the use of the `dom-input-event` would be better https://formkit.link/ddb47e028c7ee3e72c16c26f7ed72a77

**Comment by justin-schroeder** [comment]
As you saw in #267 the `@input` event should not be used as a 1-1 of someone interacting with the input. There are lots of reasons for this. Perhaps we shouldn't even have the input event if it continues to cause confusion. The input event is emitted whenever a value is committed on a node (although it is debounced for less noise). These commits intentionally take place very frequently. For example, when an input is inside a parent (`group`, `form`, or `list`) that parent will "hydrate" the child node's value. That hydration may not _change_ the value of the child, but the input event will still be emitted.

It's a fair question to ask why it works this way, I'll do my best to explain and then we can try to figure out how to target events for the side effects you are trying to do.

1. **Detecting if an input "changed" value is very expensive.** This sounds counterintuitive in the context of what we typically think of as an input, like a text input or a select list. Obviously comparing scalar values is cheap, but FormKit can store *any* type of value on an input. These can be objects. In order to compare two objects with different memory allocations you need to iterate over the object and compare each property one at a time. Because these input events are occurring on every keystroke, and even every parent's change, which means every keystroke every input in the form would need to re-evaluate if it changed, it would quickly lead to significant performance problems for anything but the simplest form. So we allow emit input events on every commit.
2. **Performing different effects based on who or what changed an input’s value is (often) an anti-pattern.** Why? Typically you shouldn't  imperatively perform an operation based on a given user action, but rather a given state. What causes the state to reach your desired target could be a lot of different things. A plugin can perform an input, the form hydrating can perform inputs, other inputs can cause inputs, and yes a user interaction can cause an input, but ideally any of these should result in the same state, and that given state is what should cause some effect to occur. For example, lets say we want to lookup a list of available states to ship a product to when the country is "usa", the trigger for performing that lookup should be when the state of the first input is "usa" — how "usa" gets populated really shouldn't be of any concern. It could be populated that way from initial hydration, it could be populated that way from some plugin, it could be populated that way by someone entering that value, but in call cases there will be an `@input` event called with the current value of the input and we can determine whether or not to perform the lookup.
3. **Hooks can modify user input.** Even if we had a 1-1 mapping to user input, a hook can modify the data a user is inputing, meaning a user-interaction even is not a reliable source of values, but the `input` event is. For example you could write a hook that changes a text value to always separate each character with a dot (a silly input mask) https://formkit.link/84fe99e594ea0714a0b3b3497d38276f in this case you want that input hook to fire even on initial hydration, because to original "value" we set is actually different than the value of the input event — so the `@input` event is a reliable way to always know the value of a given input — far more reliable than the users actual interaction.

Ok, so those are a few points on why the `@input` event works the way it does. Its for reliability and performance. Now that said, I'm sympathetic to your needing to do something potentially different than what the current system is allowing. Perhaps we can come up with a good solution for your use case or even add a new event to help meet your concern.

I think if you provided a real-world use case for what you need this user-interaction event for it would be go a long way to getting to the bottom of this. Thanks!

**Comment by justin-schroeder** [comment]
I'm closing this as inactive, but if there are some concrete reasons why we need a user-interaction event, I'm all ears and will be happy to rename and reopen this issue.

**Comment by frammkor** [comment]
> I think for your case the use of the `dom-input-event` would be better https://formkit.link/ddb47e028c7ee3e72c16c26f7ed72a77

I try this out but looks like this solution does to work on FormKit elements with the type="checkbox" as demonstrated here:
https://formkit.link/ef50cdf7f1c651da71e8e8b66df3ad81
