### ISSUE TITLE
Option to set input id to the name

### ISSUE THREAD

**Issue by JohnCampionJr** [formkit/formkit#346]
### Describe the feature

Right now, unless the id is manually specified, it is set to input_{n}.

Rather than having to use:
```
name="name"
id="name"
```

It would be nice to have id set to the same as the name.  Bit less boilerplate that way.

**Comment by justin-schroeder** [comment]
Nice suggestion, although since id's have to be globally unique I dont think we can make this a default behavior. However, FormKit’s plugin system is a pretty robust and a great fit for adding these kinds of progressive quality of life improvements. Here's a plugin that does exactly what you've suggested.

https://formkit.link/784d6cce4bb6743dbfdbe59b63507cf4

**Comment by JohnCampionJr** [comment]
That is perfect, thank you!!

**Comment by JohnCampionJr** [comment]
Here's where I ended up with a little help from lodash:

```
function autoProps(node: FormKitNode) {
  if (node.props.id) {
    node.name = node.props.id
    if (node.props.label === undefined)
      node.props.label = _.startCase(node.props.id)
  }
}
```
