### ISSUE TITLE
Schema data upates for a field trigger no data attribute updates

### ISSUE THREAD

**Issue by dominikklein** [formkit/formkit#356]
### Reproduction

https://formkit.link/1f715da8d22dd9afe2f5833253a93ff1

with "help" example:
https://formkit.link/8e6cd9d9b4b36b5ba1d1a194ca702e57

### Describe the bug

When the 'required' validation rule exists, we add an attribute `data-required` to the outer element.
For the initial schema creation, this is working fine. But when this will be updated with the schema `data`-prop the `data-required` attribute is not updated.

The same for other things which are used from the schema `data`-prop. For example when some `data-attribute` while is added, when a help text exists and the help text was updated afterward.

**Comment by justin-schroeder** [comment]
So a couple things will help clear this up:

1. Inside the schema `$node` and all its descendant properties are not reactive. If they were, it would cause a huge performance hit.
2. The `node.context` is the top level set of variables inside an input’s schema. For example in an input’s schema `$placeholder` is reading `node.context.placeholder`. However, not everything that is in `node.props` is automatically in `node.context` — they have to be explicitly declared as such. If they are not declared as such they wont be reactive within `node.context` (you can still use node methods like `node.on(`prop:propName')` to listen to changes, but they wont be automatically reflected in `node.context`/schema variables.
3. You can declare anything as a "prop" that should be synced between `node.props` and `node.context`. These don’t need to just be props declared on the Vue component, although all external props are already "synced" between node.props and node.context.

That brings us to this block of code:

![image](https://user-images.githubusercontent.com/1950463/184916094-9d923c1c-f05b-4774-a82a-a94fa51493ed.png)

Here you can see access to `$node.props.parsedRules`, so there's a 2 reasons this is not reactive:

1. It’s reading from `$node` which is not reactive.
2. `parsedRules` is not a synced prop.

To solve this, we can simply declare in our plugin that `parsedRules` _is_ a prop. That will automatically sync it between node.props.parsedRules <--> node.context.parsedRules. Since the schema reads directly from `node.context` we can now access this value via `$parsedRules` directly, and it will be reactive!

https://formkit.link/cd6a9a45d58df4c17abe503a8acffcf4

I get this is a bit confusing — the docs could be improved around the context/prop interaction, so if you have any suggestions on how we could improve the docs around that let me know, but I'll close this issue as technically its working as expected.
