### ISSUE TITLE
Mixed data types for select options behaving wrong

### ISSUE THREAD

**Issue by guyinpv** [formkit/formkit#357]
### Describe the feature

It's possible I'm just doing something wrong but I played around with it and couldn't figure it out.

When doing a select dropdown, we can provide an array of strings, or use objects to define each option in the dropdown, like so:

```
<FormKit type="select" name="Country" :options="countries" placeholder="Select Country" />
```
The `countries` variable is just an array of strings. So far so good. The placeholder gives us a typical placeholder.

Now I want to add a disabled option to act as a kind of separator between certain options, how do I do this?

```
countries = [
    "United States",
    "Canada",
    "Mexico",
// Want to insert a separator here
    "Afghanistan",
    "Aland Islands",
]
```

According to the docs, we can do alternate layouts only by using the default slot. https://formkit.com/inputs/select
However, I thought that I could just mix-n-match the different data forms, like this:

```
countries = [
    "United States",
    "Canada",
    "Mexico",
    { label: '───', value: '', attrs: {disabled: true}},
    "Afghanistan",
    "Aland Islands",
]
```

The thing is, this actually works, and it creates a disabled option after the first three countries as expected. The problem is, it kills the placeholder and instead the line I've added actually becomes the new placeholder!

![placeholder removed](https://user-images.githubusercontent.com/708955/185007613-391ffdc0-1632-408b-998c-1ac60d4a316f.png)

You can see in this screenshot that the line really does appear in the correct spot and looks just like I want it to.

![placeholder removed 2](https://user-images.githubusercontent.com/708955/185007813-1d718c0e-95b1-48d2-a3a1-c2cd90343424.png)

The question is, why does the placeholder get stripped out just because I added some other disabled option? And can I do what I'm trying to do here with a normal placeholder still intact? 
I just want the box to say "Select Country" and then have my line separate the first three.

I don't want to use the default slot idea because then I have to figure out how to cram the entire countries list into the HTML template instead of just binding it simply with the array.

**Comment by justin-schroeder** [comment]
👋 @guyinpv — the "placeholder" is just a disabled option with a value of `""`, when you created your divider line the value was also `""` so the select didn’t know which to pick and it just picked the last one — your placeholder. In this example I just changed the value to `true` — since its disabled it wont be selectable either way: https://formkit.link/8b9378534eb448c35802cfb1266316ee

**Comment by guyinpv** [comment]
Thanks, I had figured out the "selecting the last one" logic as I continued to play with it. 
In your example you actually set the value to `false`, not true as mentioned in your comment.

By setting value to `false` the HTML actually became `value="__mask_1"`. I don't know if that matters.

I kind of feel like, since the select box is choosing the "last" option with empty value as the placeholder, maybe FK should be putting its own placeholder as the last option by default? Or to say another way, is there some way to help force FK's placeholder to always win?

**Comment by justin-schroeder** [comment]
Yeah good question. FormKit is actually not selecting the empty (`""`) value — native inputs by default "select" the first item in a select — but not if that item is disabled, so the value of that list item is never actually selected. We could force FormKit to select a different value, but that would end up in the form values which wouldn't be intuative really.

Oh, and the `__mask_1` thing — select lists only support `string` values natively so when a different type is provided (`boolean` in this case) we set the raw value in HTML to a mask value and re-map the value to the original type in javascript. So yes it is intentional, but you should never see a mask value in your actual form or input values, only in the HTML.

**Comment by guyinpv** [comment]
Thanks again for expanding on this. It all feels a bit random, lol.

Perhaps the only thing to do is update the documentation because it really tripped me up and I couldn't find out why anything was behaving the way it was. The docs should explain:

1) That we can mix-n-match the list definition array with plain text and objects for various needs.
2) That the placeholder functionality of FK (set in attributes) will be overwritten if we add our own disabled fields manually.
3) How the true/false/masking stuff works.

Thanks! I suppose this issue could be closed up unless there is something to do.

**Comment by tominal** [comment]
Agreed @guyinpv. That masking effect has messed me up more times than I can count in our current project.

**Comment by justin-schroeder** [comment]
> Agreed @guyinpv. That masking effect has messed me up more times than I can count in our current project.

@tominal we haven’t gotten any other feedback about users having trouble with this so I'd love to know more about how you were getting tripped up.
