### ISSUE TITLE
References in validation is not working

### ISSUE THREAD

**Issue by nikiforovevgeniy** [formkit/formkit#362]
I want to validate the "End" field. Its value should be after the "Start" value. Please see my example on the playground. The example doesn't work. How can such functionality be implemented?

FormKit Vue Playground link:
https://formkit.link/55257ac1ab058e969fc6499cab311115

**Comment by luan-nk-nguyen** [comment]
@nikiforovevgeniy our schema parser doesn't currently parse down into arrays. If you change to the `validation` prop to be a string instead, it works! We've used schema "[Expression labeling](https://formkit.com/advanced/schema#expressions)" to build up the validation string.

Here's your example modified: https://formkit.link/3566613c7a92cef36bfdc3a68ad3d848

This is not technically a bug since it's working as written right now, but I've opened up this enhancement issue: https://github.com/formkit/formkit/issues/363
