### ISSUE TITLE
@keyup event fires late ONLY in iOS Safari

### ISSUE THREAD

**Issue by titusdecali** [formkit/formkit#367]
### Reproduction

https://codesandbox.io/s/formkit-keyup-event-is-late-on-ios-tlvf0w

### Describe the bug

I am building a complex currency swapping system with multiple inputs that change the values in the other inputs whenever one input is changed.

As such, I have to use `@keyup` to trigger methods rather than `@input`, or by watching `data()` values.
I've noticed that when firing the `@keyup` event in iOS Safari, it behaves differently than all other browsers.

In my CodeSandbox, you can see that a normal (non FormKit) input fires as expected and the value is shown in the alert.
FYI, I'm using the Options API inside of Vue3 for this.

## **EXPECTED:** 
When a keyup event fires, it should already have changed the data() value.

## **WHAT HAPPENS:** 
The value is not changed before the function is run, meaning data is 1 step out of phase. Again, this only happens on iOS and I haven't found it in other browsers or desktop environments.

## **TO REPRODUCE:**
Open my CodeSandbox on iOS and input a number. For normal inputs, it will show in the alert. For FormKit inputs, it shows nothing until after the method is finished running.

## **https://codesandbox.io/s/formkit-keyup-event-is-late-on-ios-tlvf0w**

Very bizarre.

### Environment

• OS: iOS (iPhone XS)
• Browser: iOS Safari
- iOS Version: 15.6.1
• FormKit Version: (I've tested on beta 9 and beta 10. Both have the issue)

**Comment by justin-schroeder** [comment]
Keep in mind that values are debounced in FormKit — they have a 10ms delay before the value is committed which in turn emit the `v-model` event. My guess is the browser/os debounce for a keypress is longer than that so you dont see this effect on desktop browsers. As a work around you could tap into the undebounced `_value` to get are more up to date reporting:

https://codesandbox.io/s/formkit-keyup-event-is-late-on-ios-forked-3krz9i?file=/src/App.vue

However, I want to gently push back that using `@keyup` is necessary for your use case. In fact, I think it might be an anti-pattern to perform state operations based on events rather than the state of your form. I wouldn't even recommend using the `@input` event. Ideally your entire form should be declarative, meaning the values of dependent inputs change based on the state of the form values changing rather than any particular events occurring. There are lots of things that can modify the state of a form other than keypresses and keyups that would cause your form to get out of sync if thats what it relied on.

So my suggestion would be to reconfigure the form a bit to use computed values or other reductive methods for setting dependent values.

**Comment by titusdecali** [comment]
**⚡ You've got to be setting records for the fastest issue response team on GitHub. Always impresses me! ⚡**

I'm definitely all ears to learn a better way of doing things, but am unsure of a way to use `computed` values to set inputs without it constantly overwriting them as I type.

Currently, I'm firing the event to calculate 2 of the 3 inputs at any one time, IE:

**input 1 -> set 2 and 3
input 2 -> set 1 and 3
input 3 -> set 2 and 3**

Do you think this is possible with computed values while also setting the inputs value at the same time 
(without it overwriting as the user types a number)?


**Here's the UI for reference:**
![SHOT 23 07 41@2x](https://user-images.githubusercontent.com/4532534/187222161-1599a1f7-03fa-47b8-87c5-17cf6fed43f1.jpg)

**Comment by titusdecali** [comment]
FYI, I tried `@input-raw` (which avoids debounce) but that of course causes weird other side effects because it's firing events when its own state is changed by another event (which I think you were explaining above, but with Keyup there is no issue for the same flow). 

Any possibility you'd be open to adding `@keyup-raw` similar to`@input-raw`?

**Comment by justin-schroeder** [comment]
I hear you, the thing is the `@keyup` event is the native event — we're not doing anything different there at all actually its just the the values themselves are debounced so your v-model is "slower" than a "native" v-model. Basically the existing @keyup is a @keyup raw. You can manually reduce that time by setting `:delay="0"`. I haven't tested if that would do exactly what you need.

Maybe a computed property isn’t exactly what you need, but a watcher should be. Watch specific values individually and then update the pertinent dependency nodes (via `node.input()`). My concern with using `@keyup` for state is there are lots of other ways values can be entered that would not involve key up events being fired. Drag/drop of values, accessibility devices, direct node manipulation, initial hydrations etc etc.

To be clear, I'm 100% open to adding additional events or hooks if those make sense, but I'm not sure there is one that would directly solve your issue here, and I'm still holding out hope there's a reductive state solution to your problem 🤞

**Comment by titusdecali** [comment]
@justin-schroeder I understand completely, and I didn't know about `:delay="0"`, 

Just tested it (out of pure curiosity) and it DID in fact solve the issue, and is also in the docs so I guess I have only myself to blame.

On a side note, I thought about using watchers previously, but assumed it would trigger an infinite loop. Thinking about it again now, I can see how it should in fact work and at worst would trigger the same method twice when changing any one value (once when changed via v-model, once when the watcher catches that change, but not a third time as the second time should be the same final value, IE: no change to pick up on). I'll keep this concept in mind for the future.

Thanks again for your top level support and always-friendly comments ^^
