### ISSUE TITLE
Unable to use FormKit hooks via. plugin to update v-modeled value.

### ISSUE THREAD

**Issue by sashamilenkovic** [formkit/formkit#391]
### Reproduction
FormKit Playground link: [playground](
https://formkit.link/05b9dee65f420a2c17ec321ec6e40df8)

### Describe the bug
When registering a hook via. plugin, the v-modeled value is not being updated.

### Environment
• OS: not related
• Browser: not related
• Version: ^1.0.0-beta.11-0dd967c

**Comment by GustavoFenilli** [comment]
Also it seens the hook only work once, after the first change ( both value and v-model gets updated ) but it stops working for both value and v-model.

**Comment by justin-schroeder** [comment]
There are 2 things going on here:

1. On initialization we run the input hook to ensure any plugins implementing it have had a chance to change the value. This works fine, but the v-model doesn't have syncing setup at this point so for that initial state they are out of sync. This is fixed in the latest `@next` tag.

2. Vue does not have fully "controlled" inputs — so event though the hook is setting the (internal) value of the input to 5 every time (see the v-model stays locked at 5) the input's own internal state is being overridden. We can adjust this (in vue) by explicitly setting the input’s `value` IDL attribute (`input.value = 'foo'`). This is what we'll implement in order to build out support for masking — so we'll consider that a problem for another time :)
