### ISSUE TITLE
Autocomplete - openOnClick of selectionAppearance: "option"

### ISSUE THREAD

**Issue by ThatDeveloper** [formkit/formkit#435]
### Describe the feature

It would be great if `openOnClick: true` would also open after the "x" was pressed of `selectionAppearance: "option"` autocomplete. There could also be somthing like `openAfterClick: true`.

Users would save 1 click, it would be appreciated. Especially on different devices.

**Comment by sashamilenkovic** [comment]
@ThatDeveloper I played around with this. I feel like it's a bit unnatural feeling. It makes the assumption that the user wants to reenter a different value when that may not be the case. Also, when there are multiple options to delete, it creates extra work by having to blur out of the listbox in between deletions. This is just my opinion though, so I'll leave this open.

**Comment by sashamilenkovic** [comment]
Maybe we could make a prop for it, `openOnRemove`? I'm not sure.

**Comment by ThatDeveloper** [comment]
> @ThatDeveloper I played around with this. I feel like it's a bit unnatural feeling. It makes the assumption that the user wants to reenter a different value when that may not be the case. Also, when there are multiple options to delete, it creates extra work by having to blur out of the listbox in between deletions. This is just my opinion though, so I'll leave this open.

I completely understand, that is why I would recommend using a boolean for this. openAfterResetClick or something like that.

At least for forms where a field like that is required, this would be a neat feature. :)

**Comment by justin-schroeder** [comment]
I think we want to be careful not to end up with a huge prop API here. There are literally endless possibilities for how these interactions *could* be handled, and we don’t want to end up with countless props. For sure `openAfterResetClick` should not be the prop name since describing the interaction as a `click` could have accessibility consequences — perhaps something like `open-on-remove` as @sashamilenkovic suggested could work. But I wonder if there are other similar interactions that will require additional behavior settings and if there is an elegant way to craft them all.

**Comment by ThatDeveloper** [comment]
> Instead of having multiple props for possible interactions, wouldn't be better to have events return `open` and `close` functions where the user can decide what to do with it?

How would this work in an only schema approach WITHOUT reactive data object with functions, etc?

**Comment by GustavoFenilli** [comment]
You would need to have a way to tell what you need that interaction to do, so you would have a behaviour function that is passed to the schema.

This would make the user create what it needs instead of bloating the API with n number of possibilities.

There could be a shorthand for it on the lines of `"onRemove": "$open"`.

**Comment by ThatDeveloper** [comment]
To be honest, I'd rather have a prop for this, instead of making it more difficult for a developer to do this. Because as far as I can tell this is just a simple call to open it from within the library. openOnClick is also a prop that is within the library and not a "onClick": somthing thing, right?

Also, this prop could apply to a lot of things. Autocomplete, select, maybe even date and especially custom components.

**Comment by GustavoFenilli** [comment]
But this is more of a developers needs than a library needs I believe, it could work for you, but there could be other interactions that could work for others, where do we stop adding props? as some could have bad interactions between than and there needs to be more logic on checking their inner interactions.

Instead it would be better to let the developers tell what to do with it.

Also if there are events with the functions to close and open, you could easily write a plugin that adds a prop that does what you need to do, so it would still work for N interactions and the user can write a global plugin that does your `openOnClick` and `openOnRemove` as props.

**Comment by justin-schroeder** [comment]
We’re waiting for additional feedback to see if this is a use case other people ask for. Closing this issue since it isn't currently on our roadmap.

FWIW — I think we need a better events api to easily listen for items being added/removed and allowing developers to easily implement this kind of behavior on a case by case basis. I certainly dont think there are very many people that would want this behavior, not enough to justify a stand along prop. So in that regard, I think I agree with @GustavoFenilli — but lets see if this pop up again.
