### ISSUE TITLE
TypeError: matchVariant is not a function

### ISSUE THREAD

**Issue by jerrebm** [formkit/formkit#482]
### Reproduction

Not relevant

### Describe the bug

The Tailwind plugin makes use of the new `matchVariant` API released in Tailwind 3.2, but the `package.json` is still configured to load Tailwind `3.0`, resulting in the following error:

`TypeError: matchVariant is not a function`

### Environment

Not relevant

**Comment by GustavoFenilli** [comment]
How did you get this error? using `@formkit/themes/tailwindcss`? could you elaborate a bit more?

**Comment by DamianGlowala** [comment]
Looks like in my case the following line in `@headlessui/tailwindcss` is causing this issue:

https://github.com/tailwindlabs/headlessui/blob/8b4363d7a474448078c4a996c8a97b35003767b0/packages/%40headlessui-tailwindcss/package.json#L42

**Comment by egyptik** [comment]
> How did you get this error? using `@formkit/themes/tailwindcss`? could you elaborate a bit more?

I got the error while requiring `@formkit/themes/tailwindcss` in my `tailwind.config.js` to build a custom Tailwind theme, as outlined in '[Using @formkit/themes](https://formkit.com/guides/create-a-tailwind-theme)' in the documentation.

The leading cause of this issue is probably due to the FormKit docs not mentioning anywhere that Tailwind CSS `^3.2` is required to make use of this plugin.

I figured a version bump in this project is also required since `packages/themes/src/tailwindcss/index.ts` is directly calling the `matchVariant`, which doesn't exist yet in Tailwind CSS 3.0.

**Comment by justin-schroeder** [comment]
@GustavoFenilli is our resident tailwind guru — I'll bow out of this one in favor of his sage advice.

**Comment by GustavoFenilli** [comment]
It should be fixed for `release.13`, as there are some cases that we need a way of adding group modifiers to scope the nested inputs, we need the matchVariant of `3.2` so for now just update tailwindcss to `3.2` and it should already work.

@DamianGlowala what is your opinion on how to fix nested groups and keep the version at `3.0`?
