### ISSUE TITLE
Searchable option in dropdown component

### ISSUE THREAD

**Issue by jerrebm** [formkit/formkit#495]
### Describe the feature

Please consider adding the `searchable` option to the dropdown component. I'm trying to achieve something similar to [Mantine's searchable select](https://mantine.dev/core/select/#searchable).

Although this may seem identical to an autocomplete component with `open-on-click` enabled, there is a difference:

When a value has been selected on the autocomplete, and you click on the input element to open the options list, you will only see values that match the string of the currently selected value. All other options are hidden because they don't directly contain the value of the selected input.

A searchable dropdown element would allow users to filter the options to quickly find what they are looking for without hiding any options when the input is clicked to change the value.

**Comment by justin-schroeder** [comment]
Thanks for the suggestion @egyptik! Couple thoughts on it:

1. I do think we need to be able to provide the experience you’re asking for. **It’s a valid use case.**
2. We've drawn a more distinct line between `dropdown` and `autocomplete` than other libraries have. Dropdowns in FormKit are always single value and non searchable lists, so while a `searchable` prop wouldn't be a candidate for the `dropdown` type — the experience you’re after should be possible with the autocomplete (it currently is not easily doable).
3. Manite’s dropdown with search capability is identical to our autocomplete, as you noted, with the difference of the filter behavior. We do allow the filter behavior to be modified, but it does not have enough data passed to it to perform this modified filter behavior. That behavior is: If the `searchTerm` is equal to the label of the currently selected option, perform no filter. I think we should provide a third argument to the filter that is the currently selected option (if it exists). That would give the filter function all the data it needs to easily replicate this behavior.

The more open/broader question is — why not implement this as a prop or as a default behavior? While the use case is valid, we actually think this user experience is a bit confusing because it is unclear when the list is open, and there is a search term, what will occur when a user clicks an item in the list. Is it adding an additional item? Replacing the existing one? Performing a search? This is why our UX recommendation is to use `selection-appearance="option"` which requires clearing the value before performing a search — users are well aware at every step of that process what is occurring.

OK — now, all that said — it is actually possible to produce this behavior *today* — here's an example of a plugin that provides essentially an identical behavior to manite: https://formkit.link/e6b8c1be26df09a1c9b91113f19c329f


That said — I don’t your suggestion is unreasonable at all, and we should provide a way to do it, so we'll tag this for further development! Thanks for the suggestion! 👍

**Comment by egyptik** [comment]
Thanks for the elaborate reply @justin-schroeder! 

I appreciate that you have clearly thought this through and are prioritizing the UX 😄 – I do however disagree with the conclusion. In my view, the current approach is actually making the UX a lot more confusing for the average user.

>  it is unclear when the list is open, and there is a search term, what will occur when a user clicks an item in the list

I expect it to function like any other select field. Meaning if the select field accepts a single value, I (as a user) expect it to replace the current value.

If the field accepts multiple values, I expect it to add more items to the selection (I can use the delete button to remove individual values from my selection after all).

I do not expect the input to execute a search unless I specifically start typing.

> This is why our UX recommendation is to use selection-appearance="option" which requires clearing the value before performing a search

I've tested this with two other people (tiny sample size of course!), but they were both confused as to why the input appears to be disabled right after selecting a value. And I have to agree, that is indeed what it looks like until you notice the subtle 'clear' icon. Not very intuitive and not how most users (I think) would expect a filterable select to behave.

Hence I feel like the current approach of `Dropdowns in FormKit are always single value and non-searchable lists` is unnecessary and actually degrades both the user- and developer experience. That being said, I don't have any real user data to back this up.

**Comment by justin-schroeder** [comment]
I appreciate the feedback. To some degree we'll have to agree to disagree, but the confusion around dropdown/autocomplete is semantics only and shouldn't be part of the disagreement I think. Dropdowns in FormKit are intended to mimic select lists just with more display capacity. Selects are the same way, they cannot search — but they do jump to highlight a matching selection if you type into them. Our dropdown operates the same way, if you open this input up: https://formkit.link/f5ac8c1d8dcaebe9981d8071bf9b3e50 and start typing "vue" it will jump to the correct item, just like a select would.

Autocomplete, on the other hand, helps you complete the input, thus search is inherently part of that input. The functionality you're looking for, in our lexicon, would just be part of autocomplete, not dropdown. It’s a distinction not worth spending too much time talking around. We think it’s helpful thats all. From a programatic perspective it dramatically changes the scope we don’t need to ship nearly as much code to dropdowns as we do to autocompletes.

I also think part of the UX confusion here is around the type of lists being provided in these examples. A searchable select that only provides 5 options is not super valuable, it should be a non searchable dropdown. A very long scrollable list that is searchable is less intuitive when it opens "unsearched" — its also odd that if you search for the same value that is selected, you loose the search and the full list is revealed. Again, not a big deal on small lists, but annoying on large ones.

Either way — hear me say that I'm a fan of being able to provide the experience you’re looking for. As the plugin (https://formkit.link/e6b8c1be26df09a1c9b91113f19c329f) demonstrates it is possible. Perhaps we can make it a bit simpler for people to implement. I'd even be in favor of adding an example to the autocomplete docs of that behavior.

Thanks for your quality thoughts on this 👍

**Comment by jerrebm** [comment]
> I also think part of the UX confusion here is around the type of lists being provided in these examples. A searchable select that only provides 5 options is not super valuable, it should be a non searchable dropdown. A very long scrollable list that is searchable is less intuitive when it opens "unsearched" — its also odd that if you search for the same value that is selected, you loose the search and the full list is revealed. Again, not a big deal on small lists, but annoying on large ones.

You're spot on with this 👌. I guess the problem I'm trying to solve is when the list size is arbitrary. Potentially too large for a regular dropdown, yet often too small to justify defaulting to an autocomplete. The select options are based on user-defined input, with the average user having about 10-25 values (so perfect for a dropdown), yet there are also cases in which users have created 100+ options.

Thanks for sharing the plugin! I'll have a dig into that :)

**Comment by sashamilenkovic** [comment]
@jerrebm [playground](https://formkit.link/1ccb0b1342a7ddb36843b02d64012962). Here's an example of how to do it without the plugin. Also must be @next tag.

**Comment by jerrebm** [comment]
> @jerrebm [playground](https://formkit.link/1ccb0b1342a7ddb36843b02d64012962). Here's an example of how to do it without the plugin. Also must be @next tag.

Excellent, thanks @sashamilenkovic! There seems to be an issue, though: the `node` value is never passed to the filter function.

`Cannot read properties of undefined (reading '_value')`

**Comment by sashamilenkovic** [comment]
@jerrebm Try hard reloading the playground. It's probably still referencing the last version of @next pro for you.

**Comment by jerrebm** [comment]
@sashamilenkovic Working perfectly now! 😄
