### ISSUE TITLE
How to setup i18n in Nuxt 3 - Help Needed [Beta 13]

### ISSUE THREAD

**Issue by fabiangfd** [formkit/formkit#557]
### Reproduction

-

### Describe the bug

I am having trouble getting `@formkit/i18n` to work in my Nuxt 3 project. I am using `@formkit/nuxt` + TailwindCSS and have already setup a `formkit.config.js` for my tailwind theme (which is working as intended).

in `formkit.config.js`, I am doing the following:
```
import { de } from "@formkit/i18n";
import { generateClasses } from "@formkit/themes";
...
// my tailwind theme
const theme = { ... }


export default {
    config: {
        classes: generateClasses(theme),
        locales: { de },
        locale: "de",
    },
};
```
The result: the validation error messages are still displayed in English, instead of German. What am I missing? Any help would be greatly appreciated.

### Environment

Formkit - Beta 13
Nuxt 3

**Comment by marcusarnfast** [comment]
Getting the same issue 👍🏼

**Comment by fabiangfd** [comment]
Same issue on Beta 14

**Comment by sashamilenkovic** [comment]
@fabiangfd Hey! So your locales and locale props should be one level higher, as a base prop of the defaultConfig, like this: 

`export default {
  config: {
    classes: generateClasses(theme),
  },
  locales: { de },
  locale: "de",
};`

Can you give that a try?

**Comment by marcusarnfast** [comment]
Nice that works :-) 

But am i the only one who finds the config very messy and confusing? Like why is there a "createProPlugin" and "createAutoAnimatePlugin" but not "createi18n", furthermore we do not have a createTheme but instead a "generateClasses". They are all on different levels in the config, and dont really have a system.

<img width="1715" alt="image" src="https://user-images.githubusercontent.com/99841792/214138548-e5d7826a-2ad3-4e28-adc9-b1fc15f473c9.png">

**Comment by justin-schroeder** [comment]
I think your critique here is valid — certainly we could try to make this more streamlined. That said, there is a logic and system behind what you are seeing.

The values you are setting up here are passed to `defaultConfig` — which does what it says on the `tin`, it is a default configuration but certainly not the only configuration. All the features you are refering to, like `i18n` *is* a plugin and does have a `createi18nPlugin` (for example: https://github.com/formkit/formkit/blob/master/packages/i18n/src/i18n.ts#L60).

However, since most people want to use these plugins on most projects, they are setup for you if you choose to use the `defaultConfig`. You can, of course, opt out of the `defaultConfig` and set these up for yourself which is great for tree shaking and performance tuning.

If you want to see what all defaultConfig is doing for you, you can take a peek here: https://github.com/formkit/formkit/blob/master/packages/vue/src/defaultConfig.ts#L45-L94
