### ISSUE TITLE
'name' attribute is not changed when using conditional schema

### ISSUE THREAD

**Issue by davimatos** [formkit/formkit#570]
### Reproduction

https://formkit.link/d1fb77fac4d1e1ab03db399f51088861

### Describe the bug

Hi!

I'm using a 'select' component with two options in conjunction with two fields with conditional display.

The proposal is simple: If the value of 'select' is 'refresh', 'field1' is displayed, if the value is 'hourly', 'field2' is displayed.

The alternation of fields happens, including changing the label. However, the 'name' attribute of the input is not changed, remaining 'field1'.

### Environment

• OS: Linux (PopOS)
• Browser Google Chrome
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
@davimatos this sometimes happens when vue gets "confused" about the vdom structure to render, you can slap a `key` on the components to resolve it though:

https://formkit.link/a0c61537d3cbffec4e637efdcf0ba539

Fundamentally, under the hood, this is related to #528 — so ill close this in favor of that.

**Comment by davimatos** [comment]
> @davimatos this sometimes happens when vue gets "confused" about the vdom structure to render, you can slap a `key` on the components to resolve it though:
> 
> https://formkit.link/a0c61537d3cbffec4e637efdcf0ba539
> 
> Fundamentally, under the hood, this is related to #528 — so ill close this in favor of that.

Thanks, Justin!
