### ISSUE TITLE
You cannot v-model a `reactive()` value directly

### ISSUE THREAD

**Issue by tosling** [formkit/formkit#58]
**Describe the bug**
When (v-model) binding a reactive() object to the `<FormKit type="form">`, it will loose it's reactivity almost completely. 

Using a ref() instead is working and even updates the reactive object when changed.

The examples in the documentation use ref(), but I'm wondering whether reactive shouldn't work as well, since it's common to use reactive() for objects.

**Reproduction**
1. Open Playground: https://formkit.link/d3506792267c1eb4909331f1695d288c
2. Enter something in the **first field** -> most likely nothing will happen or only first 1-2 letters will be output above the field.
3. Enter something in the **second field** -> the input is displayed almost immediately (as expected) and also the input from the first field is shown.
4. Repeat the same with the **third field** -> again no updates, only after the middle input is changed.

**Desktop**
 - OS: Mac 11.6.2
 - Browser: Chrome 98.0.4758.80

**Comment by tosling** [comment]
Hi @justin-schroeder, 

thanks for the super fast reply. 

I think I need to dive a little deeper into FormKit's code, to fully understand the limitations or maybe find a nice solution. 

In theory:
- I would expect, that FormKit (our `<FormKit type="form">`) somehow propagates the v-model value down to the children nodes (`<FormKit type="input">` in our case). 
- Then in the child node, you assign the value via `ref.value`. 
- Wouldn't it be possible, to check if we have a `Ref` or a `Proxy` (created by reactive()) and if it's the Proxy, then access the property directly?

**Comment by justin-schroeder** [comment]
You would think so, right? Perhaps there is some way to kinda "fake" our way there to help improve the dx on that — but fundamentally it's not really how the v-model contract works. Effectively v-model takes the emitted value and[ directly assigns it to the value](https://github.com/vuejs/core/blob/9c304bfe7942a20264235865b4bb5f6e53fdee0d/packages/compiler-dom/src/transforms/vModel.ts) `vModelValue = $emitttedValue`. This is fine when the `vModelValue` is a ref, because the template compiler knows to assign it to `vModelValue.value` instead of the root object, but `reactive` is not wrapped to it attempts to perform a wholesale replacement of the `vModelValue` itself, (which is often a `const` anyway).

Coming from the options api, this would be like trying to v-model the entire `$data` object, instead of a single property within it. [Here’s a simple example](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZXMgPSByZWFjdGl2ZShbXSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8bGFiZWw+XG4gICAgQVxuICBcdDxpbnB1dCB0eXBlPVwiY2hlY2tib3hcIiB2YWx1ZT1cImFcIiB2LW1vZGVsPVwidmFsdWVzXCI+XG4gIDwvbGFiZWw+XG4gIDxsYWJlbD5cbiAgICBCXG4gIFx0PGlucHV0IHR5cGU9XCJjaGVja2JveFwiIG5hbWU9XCJiXCIgdi1tb2RlbD1cInZhbHVlc1wiPlxuICA8L2xhYmVsPlxuICA8bGFiZWw+XG4gICAgQ1xuICBcdDxpbnB1dCB0eXBlPVwiY2hlY2tib3hcIiBuYW1lPVwiYlwiIHYtbW9kZWw9XCJ2YWx1ZXNcIj5cbiAgPC9sYWJlbD5cbiAge3sgdmFsdWVzIH19XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0ifQ==) of this at play in pure vue.

So ways to work around it? We could do what you’re saying and detect if we are working with a `reactive` vs a `ref` object — and then essentially _not_ emit the `update:modelValue` event, and instead directly manipuate the `modelValue` ref — but prop manipulation is generally frowned upon and will emit warnings from Vue.

So, I'm definitely open to suggestions on how to improve this, because fundamentally I agree with you that making it magically work with `reactive()` would be a much better DX, but at the moment I feel like our hands are tied — plus it's pretty easy to just use a `ref()` or a property of the reactive object.

Still — open to ideas, I'll leave this open for now. 👍

**Comment by tosling** [comment]
Thanks for the excellent explantation @justin-schroeder 👍 Very valuable information. 

This should at least help others facing similar situation.  - and I agree, `ref()`s work pretty smoothly with FormKit, although there is the necessity of `.value` here and there.

Will keep thinking about a magic solution. ;)

**Comment by GustavoFenilli** [comment]
> This should at least help others facing similar situation. - and I agree, `ref()`s work pretty smoothly with FormKit, although there is the necessity of `.value` here and there.
> 

I think that is why vue is going to implement sugar syntax for this using Reactivity Transforms. https://github.com/vuejs/rfcs/discussions/369

indeed using .value everywhere is quite ugly.
