### ISSUE TITLE
Repeaters with conditionals don't work

### ISSUE THREAD

**Issue by addidesign** [formkit/formkit#583]
### Reproduction

https://formkit.link/8727e24479ef86823cd5a8bf8ded87f5

### Describe the bug

Firstly, thanks for making such an awesome framework for forms!!! 

I know that any conditional needs a unique id to check against but is there an out-of-the-box way to handle repeater field ids with conditions relating to the current repeater? 

In the playground example you can see that setting the dropdown to 'Something' will trigger changes in all additional repeaters. 

Is the correct approach to create a reactive function to construct an unique id, like below, or is there a better way? 

`id: '$uniqueId(field_key_, $index)'`

### Environment

• OS: iOS
• Browser chrome

**Comment by GustavoFenilli** [comment]
For this case instead of getting using `$get` you can just get the current `value` of the repeater and check for that, as values are passed downwards. 

so your line `$get(things).value === Something` change to `if: '$value.things === Something',`.
https://formkit.link/98219e1f16c5d752a20c67dbfa47986f
