### ISSUE TITLE
Blur event does not fire on checkboxes in Safari

### ISSUE THREAD

**Issue by johnson0903** [formkit/formkit#593]
### Reproduction

https://formkit.link/05d53379747a1b67be1ea103fba37fc0

### Describe the bug

**Must open the playground on real iOS device to reproduce the issue.**

Expect to show the required error message after uncheck the checkbox. 
Also test it with other rules on checkbox, such as `min`, and didn't work either.

### Environment

• OS: iOS 16.3.1
• Browser Chrome  v109.0.5414.112 and safari

**Comment by johnson0903** [comment]
Also happend on macbook safari 16.2

**Comment by justin-schroeder** [comment]
🤔 — seems like the `blur` event doesn't trigger the same in safari on checkboxes. As a temporary workaround you can set `validation-visibility="dirty"`

https://formkit.link/2b5a90b1a53f6fd5dca81626fef4d2c7

**Comment by johnson0903** [comment]
https://user-images.githubusercontent.com/16976349/221221308-2208378d-9b7a-4064-b4e5-9a6a1e0d951a.MOV

Not only safari, chrome doesn't work either.

**Comment by justin-schroeder** [comment]
After some research it appears that safari does not allow focusing of checkboxes. It’s a long documented issue that seems likely to never change. That said, users who need keyboard control over such things can enable it on a per-device basis (Search system settings for "Full Keyboard Access"). "This is the way" apparently, so not much we can do about it. However, in response to this we are changing the default `validation-visibility` from `blur` to `dirty` for checkbox inputs in >= 0.18.0. This should result in a more consistent experience, and is not really a noticeable change from blur since checkbox blurring only occurs after input anyway.
