### ISSUE TITLE
Missing icons in @formkit/icons@1.0.0-beta.15

### ISSUE THREAD

**Issue by jfbloom22** [formkit/formkit#597]
### Reproduction

NA

### Describe the bug

Some icons are missing from @formkit/icons@1.0.0-beta.15.   I am missing check, circle, spinner, star, in node_modules/@formkit/icons/dist/index.d.ts

more info:
I am installing via Yarn 3.
Reverting to @formkit/icons@1.0.0-beta.14 resolves the issue.
The playground for beta-15 does not have the same issue.
When I build formkit locally from the beta.15, it is Not missing the icons.  

It appears that something went wrong when publishing to NPM.
Andrew Boyd suggested I create an issue for this:  https://discord.com/channels/793529058377072650/1025447518617735210/1080245549892128828

### Environment

• OS: Mac 12.6.3
• Browser: NA - this issue is seen in the files downloaded via NPM
• Version: @formkit/icons@1.0.0-beta.15

**Comment by andrew-boyd** [comment]
So looking at the actual files on npmjs.org it appears that the icons are all accounted for: https://www.npmjs.com/package/@formkit/icons?activeTab=explore

Possible this was a dependency resolution error? We've had reports of users installing `beta.15` and getting `beta.9` in their lockfiles for dependencies because the module resolution has a hard time telling that `beta.1_` is greater than `beta.9`.  We're changing our versioning to `0.16.0` starting with the next release to help address this.

If you change your `packaged.json` to use the `latest` tag as your preferred version do you get the icons as expected?

**Comment by andrew-boyd** [comment]
I'm closing this, feel free to re-open if it's still an issue.
