### ISSUE TITLE
Resetting dynamic lists with empty arrays

### ISSUE THREAD

**Issue by csakis** [formkit/formkit#636]
### Reproduction

https://formkit.link/bedd635f631efb22795c7c3f69d0a744

### Describe the bug

I use a dynamic list to keep track of an unkown numbers of objects. Whenever I reset the list to an empty list under the hood Formkit creates an array that is filled with the same number of `null` as long as the previous list was before the reset, instead of giving me an empty array.

### Environment

Windows 10 Pro
Microsoft Edge v111.0.1661.54

**Comment by mathsgod** [comment]
I guess that problem is due to there are values in `list` before mount, which casued the core of formkit create two input node.

The another problem is reset, If just reset by set the `list.value` to `[]`, I guess the `<form-kit type='text'>` still haven't update before the `<form-kit type='type'>`  updated. It cause the formkit core re-create the value with `null` for those `<form-kit type='text'>` in node list.

I had refined the javascript code by add values after `mouned` and reset list value by set `list.length = 0` to temporary solve the problem.

https://formkit.link/06ebccd48c24feec9d5655bb7a86a786

**Comment by GustavoFenilli** [comment]
Well @mathsgod is kinda right in that when you change the array of values the nodes aren't being deleted at the correct time, so it removes the values, but not the nodes.

I would say that you should `iterate over a list of items, not a the list of values, let FormKit take care of the reactive state of the form instead.`

https://formkit.link/ae396eb07d90d5ca27a14ebf66eeceb1

**Comment by csakis** [comment]
Let's complicate the issue a bit more. If the user wants to delete an element from the array, then, the deletion will be replaced with  a `null` value.
https://formkit.link/22cdd25e80a1c1e38e38fae1460c60f5

**Comment by GustavoFenilli** [comment]
> Let's complicate the issue a bit more. If the user wants to delete an element from the array, then, the deletion will be replaced with a `null` value. https://formkit.link/22cdd25e80a1c1e38e38fae1460c60f5

Like I said in the previous answer, try no to iterate over values of the list, but iterator over a list itself like so https://formkit.link/86704a4a1e3821c8b5a014097eca5e66

**Comment by csakis** [comment]
@GustavoFenilli Try adding and deleting emails in your solution!

**Comment by jm-sky** [comment]
FormKit is very useful but I also have problem with lists.
I have form for an invoice with many fields, and also with `lines` field - **an array of objects.**

When I try to delete a row, I get `Uncaught (in promise) Error: Cannot set 3 to non object value: undefined` error.

I'm using `v-model` on form because I need to update values in some cases (changing country changes currency etc).
When I try to use `:value` on form, I can't update form's values.
I also can't `watch` forms state (`watch(formRef.value.node.value, () => callback())` is not working).

Maybe I'm missing something?

Simplified example here:
https://formkit.link/ab4872368e04222d7346b2ed2b699db3

**Comment by GustavoFenilli** [comment]
Well for your case you're setting the items with lines as name inside the form, and that is being passed to the list called lines as values, so in the end you end up iterating over list values, and that causes some problems.

I would change your logic from using v-model for the model to using events/hooks for changing values instead, and make the v-model only for creating the iteration part of the list ( can create a component to make that easier to deal with ).

**Comment by justin-schroeder** [comment]
There is now first-party support for dynamic lists. You can read about them here: https://formkit.com/inputs/list
