### ISSUE TITLE
Nuxt module improvement suggestions

### ISSUE THREAD

**Issue by pi0** [formkit/formkit#67]
Thanks, @justin-schroeder for creating a nice Nuxt module. I've spotted few items that could be improved regarding config loading.

Config files should be resolved from `rootDir` rather than `srcDir`. You can use `resolvePath` utility from `@nuxt/kit` to easily resolve it, respecting supported extensions. [example](https://github.com/nuxt-community/tailwindcss-module/blob/c133da8db34eccae1e1605e215156a25ea5b6de5/src/module.ts#L42)

It would be so nice to reduce dependency on templating as much as possible. [this error](https://github.com/formkit/formkit/blob/7cb9e3b840316eb5cffab36fa9ecff4248826e3c/packages/nuxt/src/runtime/plugin.mjs#L14) for instance could be directly thrown in the module instead of delegation to runtime and `defaultConfig` can be set as default value for `configFile` in module.ts.

Config could also be directly imported in module using `requireModule` utility and passed as options object. This not only reduces depending on templating, but also improves build time by avoid transpiler and gives more possibilities to validate config in build time or extend it with other modules.

Would be also nice to also add `compatibility` field in `meta` field to indicate only Nuxt ^3.0.0 with vue3 is supported.

**Comment by justin-schroeder** [comment]
Thanks for the feedback @pi0! We'll make these changes soon.

**Comment by justin-schroeder** [comment]
@pi0 — I refactored most of the module in [this most recent push](https://github.com/formkit/formkit/commit/0cbfab5897a9f9ec80ef05bcc752cd30140525d9) — including using `resolvePath` and reducing the templating significantly. It now only has 2 simple template outputs. Honestly I would love to get rid of the template all together, but as far as I can tell there is no way to pass functions and other non serializable data to a nuxt plugin from a nuxt module using `addPlugin` (or is there?). 

FormKit uses lots of user-defined functions in its configuration (like plugin functions for example) — so as far as I know, I still need to use the template to "manually" write those `import` statements (is my assumption true?)

**Comment by pi0** [comment]
Amazing work @justin-schroeder ! Added two comments to https://github.com/formkit/formkit/commit/0cbfab5897a9f9ec80ef05bcc752cd30140525d9 hopefully solving template issue.

**Comment by justin-schroeder** [comment]
@pi0 — ok, played around with the `nuxt.options.alias` a bit to try and fully remove the template — but I've fallen short. I need to import a named import (`import { defaultConfig } from '@fomrkit/core'`) based on the module option `option.defaultConfig`. So for example, the final template output could be 1 of 3 variations:

## 1. No configFile or detected config file provided:

```js
import { defineNuxtPlugin } from '#app'
import { plugin, defaultConfig } from '@formkit/vue'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(plugin, defaultConfig)
})
```

## 2. `formkit.config.(ts|mjs|js)` exists and `defaultConfig` is `true` (default)

```js
import { defineNuxtPlugin } from '#app'
import { plugin, defaultConfig } from '@formkit/vue'
import config from './path/to/formkit.config.ts'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(plugin, defaultConfig(config))
})
```

## 3. `formkit.config.(ts|mjs|js)` is `false` and `defaultConfig` is `false`
In this case they provide the entire config setup, so we don’t import `defaultConfig` at all:

```js
import { defineNuxtPlugin } from '#app'
import { plugin } from '@formkit/vue'
import config from './path/to/formkit.config.ts'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(plugin, config)
})
```

If I understand correctly, I can alias `import config from '#formkit-config'` to be the path to `formkit.config.ts` file which solves 1 import question, but doesn't solve the variability of the named `import { defaultConfig } from '@formkit/vue'`. If users dont want the `defaultConfig` I dont want to import it since it includes a lot of default weight people may not want to absorb.

Is this a use case for keeping the template around, or are there other paths forward?

**Comment by pi0** [comment]
We can think of some ideas to alias config to an empty alias (like `#empty`) but we could also use a dynamic import template from the module:

```js
addTemplate({
  fileName: '#fromkit-config'
  getContents: () => { /* dynamic logic to generate exportstatement */ return 'export default ...' }
})
```

This way we can still avoid lodash template in plugin while having full control over logic.

**Comment by andrew-boyd** [comment]
We've been able to remove the lodash templates in the latest release. Closing this one!
