### ISSUE TITLE
Off by one error with @input in beta.17

### ISSUE THREAD

**Issue by mjlehrke** [formkit/formkit#706]
### Reproduction

https://formkit.link/1d5ef75896bef983ca6160126f7dea55

### Describe the bug

The most recent beta version introduced an off-by-one error when using @input on a FormKit field to do something with the input value.

In the reproduction example, the two values "query" and "thisIsOff" should be the same, but they will be off by one character. 

This worked as expected in beta.16. (see here: https://formkit.link/8ed8cc55355de6b6de1318839f54ec9c )

Interestingly, the v-model seems to be updated appropriately. But any use of the v-model in the @input function will use the previous value. Is @input firing before the v-model is updated? Or is this related to "noise" changes mentioned in the changelog? 

### Environment

• OS: Windows 11
• Browser FireFox
• Version 103

**Comment by justin-schroeder** [comment]
I believe this is actually operating as expected. The `@input` event fires *before* the v-model event (`@updated:modelValue`) — so when you are setting your new ref `thisIsOff.value = query.value` in the input event handler you are storing the old value. However, you can see in the example below that your input event is being called with the correctly updated value. So this has to do with sequencing rather than a bug.

Previously the `@input` event was very "noisy" (it just fired all the darn time), and it was debounced which may have been masking this underlying reality. Here’s a working example:

https://formkit.link/a32668b8616a25b77c1cc42b98114bd4

**Comment by mjlehrke** [comment]
Thanks for the info.
