### ISSUE TITLE
Config ignores custom pasword component

### ISSUE THREAD

**Issue by hrubysi** [formkit/formkit#719]
### Reproduction

https://formkit.link/c75facd96647819d633fdc3e23695371

### Describe the bug

I am unable to set custom input component to `password` globally. 
Password always uses `text` input component.

See reproduction.

```
inputs: {
    text: createInput(TextInput),
    password: createInput(PasswordInput),
  }
```

### Environment

• OS: Windows 11
• Browser Brave
• Version v1.51.114

**Comment by justin-schroeder** [comment]
This does look like a bug indeed — so we’ll fix it in an upcoming release. That said, the issue here is that the `text` and the `password` input have the same `schemaMemoKey` because when they are not overridden in this way they share identical schema (the `type` is just a dynamic variable), so the schema is memoized and recycled for performance reasons.

When you re-assign an input like that you are actually performing a merge, not a wholesale replacement it actually merges the two definitions together. This is not intuitive, so I've published a fix on the `@next` tag that will make its way into `0.17.2` — however in the meantime we can just provide an alternative `schemaMemoKey`. Here’s your example working:

https://formkit.link/3873f7c9ceb49815bb653a1cd35baa55
