### ISSUE TITLE
Input event is off by one

### ISSUE THREAD

**Issue by Vant0** [formkit/formkit#749]
### Reproduction

https://formkit.link/dcf50e6d22951d728606b482d5259e6a

### Describe the bug

The goal of this code is to trigger an alert when the first character is typed in the input field by using the programmatically submitting method.
Up to and including Beta 16, this is working. From Beta 17 and upwards, I need to input a second character before the alert is shown.

### Environment

• OS: macOS Ventura 13.4
• Browser: Brave [Version 1.52.117 Chromium: 114.0.5735.90 (Official Build) (arm64)]
• Version: -

**Comment by andrew-boyd** [comment]
As a temporary work-around you can wrap your submit call in a `1ms` setTimeout. https://formkit.link/89c2a9c8623df6235ebd287265896a2b

**Comment by Vant0** [comment]
I am not sure, the bug is related to the input event. I have made another example which is closer to how I am using it in my project. Maybe it helps.

[FormKit Playground Link](https://formkit.link/03a8402730ad414d0e3922581e1be6ea)

**Comment by justin-schroeder** [comment]
Ok, after spending some time looking at this it actually makes sense — since you’re using a vue watcher on the data object, it is firing the instant the internal value changes, this occurs before the validation has had a chance to complete so your state is one step behind. There is no specific error here, that said if you want to know anytime your form has settled and all validation rules are passing you can listen to the `settled:blocking` event: https://formkit.link/e7b6732b0a83afefd6079cc643eeceb5
