### ISSUE TITLE
model-value support, not only modelValue (kebab case)

### ISSUE THREAD

**Issue by CavalcanteLeo** [formkit/formkit#785]
### Describe the bug
eslint complains about camelCase, to use kebab-case instead.. and there is one validation that only looks for camelCase

the code:
https://github.com/formkit/formkit/blob/2e81d151a69eb3a846abad5d64787ac10e8ea46d/packages/vue/src/composables/useInput.ts#L173

should also allow `model-value`

### Environment

• Version [Beta 17]

**Comment by JoaoPedroAS51** [comment]
This is really tricky because of eslint rule `vue/attribute-hyphenation`. So without the proper support for expanded v-model, we need to disable the rule for the input in order to be able to use it.

A common use case is when we need to do some stuff before saving the value. So we call a function on `input` event.

```vue
<script setup>
const myValue = ref()
const updateValue = (newValue) => {
  // Do stuff...
  myValue.value = newValue
}
</script>

<template>
 <FormKit :model-value="myValue" @input="updateValue" />
</template>
```

**Comment by CavalcanteLeo** [comment]
PR:

https://github.com/formkit/formkit/pull/786
