### ISSUE TITLE
Updating a `form` with `v-model` breaks `repeater` under certain conditions

### ISSUE THREAD

**Issue by nhedger** [formkit/formkit#794]
### Reproduction

https://formkit.link/5da0c8fd5c4557ac946407fd1018a5d6

### Describe the bug

When [creating an uninitialized `form`](https://formkit.link/f8e39fd4bb30ebcbd0065a9ce6e1c74a) with a `repeater`, the repeater shows at least one item, allowing us to directly input without clicking on the *add button*, but when initializing the form with some data using `v-model` or `node.input`, if the value of the repeater is an empty array, no items are shown, meaning that if `add-button` is set to false, we cannot interact with the repeater.

- Using `v-model`: https://formkit.link/5da0c8fd5c4557ac946407fd1018a5d6
- Using `node.input`: https://formkit.link/1f5f4df8d445af389c5ea261c23173a1

### Environment

• OS: macOS 13.3.1 
• Browser: Firefox 
• Version: 114.0.2 (64-bit)

**Comment by nhedger** [comment]
Gotcha, thanks for providing an example.

I wasn't aware of this behaviour, but it makes sense now that you mention it.

I think adding a line regarding this in the documentation would be a good idea. I'll see if I can send a PR.

**Comment by nhedger** [comment]
@justin-schroeder

Just to make sure, when you say that this is the intended behavior, is there a reason why the repeater render an item when initializing the repeater with an empty array using `:value` ?

I would think this also falls under "_you are explicitly requesting the form be set to an empty array_".

Here's an example: https://formkit.link/0067615c7e3c87a4b61206875741f8af

**Comment by justin-schroeder** [comment]
At instantiation the repeater ensures that there are *at least* the `min` number of items in the array, if there aren’t it fills the array up till it reaches that number (https://formkit.link/6fbb1770c496725929119109690f6ea7). However after the repeater boots up if you explicitly change the value (via `node.input` or `v-model`) to something lower than the `min` it assumes that was an intentional decision on the developer’s part and allows it. The UI on the other hand does not allow a user to go over/under the min/max props. Again, that behavior can be modified via plugin.

Hope that clears up any confusion 👍

**Comment by nhedger** [comment]
Thanks for the clarification, all clear now. Thanks for taking the time.
