### ISSUE TITLE
Simpler way to set errors after form submission

### ISSUE THREAD

**Issue by huzaifahj** [formkit/formkit#80]
Not sure if it's just me, but the process of showing errors on a form is a bit cumbersome:

1. `import { setErrors } from '@formkit/vue'`
2. Set a unique ID on your form
3. Invoke `setErrors()` with your unique ID

What if the form submission handler was passed a second parameter containing a node object?

```js
function submit(value, node) {
  node.setErrors(["Username not available."])
} 
```

Implementation details free to be changed but something like this.

**Comment by tosling** [comment]
I'm not a fan of using the form's id as well. (and of course one could use [the errors prop](https://formkit.com/essentials/forms#form-errors) as an alternative.

I don't think that passing a reference to the node object would be the best approach here, this would only work if you are using the build-in form submission or be cumbersome again, if you wanted to manually pass that reference. 

Adding another idea here: What about using `ref`s instead of the form's id? It wouldn't solve #1, which is quite a common thing working with Composition API anyway. And the rest is pretty much in line with vue standard practice.

**Comment by huzaifahj** [comment]
@tosling Could you give an example of what your proposed way of using `ref`s would look like?

This issue is aimed at streamlining the error-setting process when using just the `@submit` event. Otherwise, I think the `setErrors` way is quite a reasonable way of handling things manually.

**Comment by tosling** [comment]
I was thinking of something like this, to avoid using the form id.

```vue
<template>
  <FormKit type="form" ref="myForm" ...>
  ...
</template>

<script>
const myForm = ref()

function mySubmitFunction() {
  /* do some communication with server with error here */
  myForm.setErrors(...)
}
```

But thinking a bit further, your approach, combined with feature request #82 (submitting forms programmatically) should be very powerful and can avoid all the manual referencing.

**Comment by tosling** [comment]
Using IDs is great, mainly when writing native JS, and als long you can guarantee they are unique.

I see some challenges, when it comes to re-using components (e.g. a create vs. edit form; I could think of other examples). For those cases, I prefer having the scope of my components as limited as possible. And that's where my approach conflicts with your no. 4.

During my tests I had some cases, where setErrors didn't work, because the form ID was already in use. I can not yet say, if that was a caching issue on my development environment or whether it's a real case. Creating a realistic reproduction would take a bit more work (nested routes were involved in my tests), which I postponed for now.

For me personally, I would be happy with @huzaifahj suggestion, as it solves the "ID" topic for me. 👍 

PS: Another 👍 for the error adapter, although at least in the Laravel case that's no big issue right now.

**Comment by justin-schroeder** [comment]
@tosling solid points — one thing to note that will help with the unique ID thing is FormKit already produces unique IDs for you — you technically dont need to specify it yourself — but only explicitly specified ones end up in the global `getNode()` registry.

For submitting forms, which is now in the beta.3 branch as of a few minutes ago, you can submit these forms 3 ways:

```
// any id works, even the auto-generated ones
submitForm('formId')
$formkit.submit('formId')
node.submit()
```

An alternative way to get a node is using the `@node` event which is emitted from all `<FormKit>` components with the node as a payload. And in beta.3 you can also get the node via template ref:

```
<template>
  <FormKit ref="foobar" />
</template>

<script>
export default {
  mounted () {
    this.$refs.foobar.node.input('hello world')
  }
}
</script>
```

[Playground example](https://formkit.link/0051f6d83033f442ff335ec8037780fa)

**Comment by huzaifahj** [comment]
Thanks, looks great @justin-schroeder! It might be nice if `setErrors()` could accept a string as well as an array, unless there is a good reason for that which I'm not getting?
