### ISSUE TITLE
Usage of classes inside bind schema are not reactive

### ISSUE THREAD

**Issue by dominikklein** [formkit/formkit#828]
### Reproduction

https://formkit.link/1426dad27582d507db7df5380194c049

### Describe the bug

Classes inside the usage of bind schema are currently not reactive.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by nclemeur** [comment]
I was just playing with that example and found out that a possible workaround is to initialise helpClass in the schemaData with any value (or even null)

**Comment by justin-schroeder** [comment]
Unfortunately I think this is a fundamental limitation of how the these "wildcard" props work in FormKit — the `*-class` or `*-icon` props, for example, need to *exist* when the input is initialized in order to be tracked as props. Setting the prop to *any* initial value will let FormKit know it needs to track it.

For now I’m going to mark this as `wontfix` since there is no performant mechanism beyond that. If this is a showstopper for someone, perhaps we can investigate further.
