### ISSUE TITLE
Custom submit button won't get disabled during request

### ISSUE THREAD

**Issue by oerol** [formkit/formkit#916]
### Reproduction

https://formkit.link/eaefa52d623ff4786d42b578fa801dde

### Describe the bug

The custom button element that is used to submit the form does not get disabled during a request. 

In the given example it's possible to press the button multiple times, which is not what we want. The generated FormKit button however, gets disabled correctly.

### Environment

• OS: MacOS
• Browser: Chrome
• Version 0.18.x

**Comment by justin-schroeder** [comment]
Thanks for filing an issue — we don’t currently consider this a bug since we think it makes sense to give the developer control over the submit button if they have chosen to use their own. You can still easily replicate the behavior by using the `loading` property from the form’s default slot’s data. Checkout this preceding issue for more information: https://github.com/formkit/formkit/issues/236
