### ISSUE TITLE
Datepicker’s min-date is not reactive

### ISSUE THREAD

**Issue by justin-schroeder** [formkit/formkit#976]
### Reproduction

https://formkit.link/61c524e0448a6f684dc5d59942572b15

### Describe the bug

Currently the min-date does not respond to dynamic changes to its value — this makes using the datepicker for dateranges difficult.

**Workaround**: You can use the `disabled-days` to manually take control of dynamically disabled days: https://formkit.link/bbca35415b2b936625fa1abcbf95a659

### Environment

• OS: macOS
• Browser: Safari
• Version: 1.2.0 and 0.117.0

**Comment by KoenCa** [comment]
I'm in a situation were this is causing me some headaches. In my situation there are two **disabled** datepickers that represent a period and there are initial values coming from query params in the URL for both of them. There is also a props passed in from the parent that determines if they should be disabled or not. This prop is also reactively used in the `min-date` prop of the datepicker. So, because `min-date` is not reactive there is still an "old" `min-date` validation applied which is what this issue is about. So I tried to implement the workaround, but the problem is that this doesn't really work for disabled inputs. It looks like the `disabled-days` callback is only called when the input it is set on changes, but since it is disabled and gets an initial value it is triggered just after mount when the "old"/invalid `min-date` is still applied resulting in my form being invalid. I would think that it is at least rerun when I submit the form, but sadly this isn't the case. Otherwise it wouldn't be a problem I think. I have a reproduction based on your playground link to showcase that an invalid form can be submitted with your provided workaround.

https://formkit.link/75b2c4c96d5faa7c0d5c5cc7b147837f

**Comment by sashamilenkovic** [comment]
@justin-schroeder Min and max dates should now be reactive at FormKit Pro v0.126.6
