### ISSUE TITLE
Can't choose option after options have changed via a schema

### ISSUE THREAD

**Issue by smakinson** [formkit/formkit#994]
### Reproduction

https://formkit.link/21a1857c03a7a50b4348114fc2f20543

### Describe the bug

When using a schema with a `select` and the options are bound to a reactive data value, an option can be chosen, but when the options are changed via the reactive data, the new option is shown, but is not selectable and is shown dimmed a bit. It may be related to if a `placeholder` is used. @andrew-boyd requested this issue be opened via discord.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by GustavoFenilli** [comment]
Not sure if its a bug or a unintended behaviour because of how it works, because when you change options, it won't remove the selection or change the value, meaning it will by default have something selected in the dom but the value isn't changed, and you can't deselect a select.

for that I wouldn't use a reactive data, I would use an ID get the node and change it directly using schema, and also adding the new value or undefined after options change like so: https://formkit.link/2fd28d52a30bb0354a968dd95b68a066

**Comment by smakinson** [comment]
@GustavoFenilli  Kinda funny, I landed back on using reactive data since I can't pass a function that passes the value of another input and returns a Promise to the options within the schema. I had a feeling the reason above may be what is going on. Does the how it works mean it's not possible to have it auto reset the value on options change, say if a prop said to do it? (I suppose there would be a time for that and a time where we would not want that) I'm mainly thinking about logic in the component I have not knowing anything about the schema being used.

**Comment by smakinson** [comment]
One thing I noticed, is if I comment out the `placeholder` prop in the repro link, the issue does not seem to be there.

**Comment by smakinson** [comment]
I'm going to start working in a direction indicated by your playground link, but what do you think about this, maybe this is the bug:

If there is a placeholder, and the options change, but the current value does not match an option, the placeholder should be shown again.

If the above happened, the value may still be the previously selected value, but the input would behave as expected so far as interacting with it. Then if that leaves the need for manually resetting the value as a separate question.

**Comment by GustavoFenilli** [comment]
The thing is, the default is that it doesn't change the value no matter what, the reason why it works in my example by removing the placeholder is because when you do undefined to a select that does not accept undefined, it probably defaults to the first value in the options.

There was already a conversation about this behaviour and if i remember correctly it was indeed the correct behavious.

But for your case that you want that behaviour it is easilly added with a plugin that whenever options change you can check if the value exists and maintain, or give undefined to it: https://formkit.link/dd5ae2dac910410f64ada66eb975c4f0

**Comment by smakinson** [comment]
Ok thanks for talking this through. I'll take a look at going that route.
