### ISSUE TITLE
Removing item from the dynamic list does not work properly when using schema

### ISSUE THREAD

**Issue by KamilBeda** [formkit/formkit#997]
### Reproduction

https://formkit.link/ab5eb25fc3a7f6e3a68cc19ac5670e18

### Describe the bug

If I enter value inside intermediate input and click remove all items below get removed. It works correctly when there's nothing inside inputs. 

Steps to reproduce: 
- Add 4 items
- Enter value inside second input
- Click remove button below second input
- Watch how all inputs below get removed

[Related discord discussion](https://discord.com/channels/793529058377072650/940340536747896842/1163682117285331035)

### Environment

• OS: [N/A]
• Browser [N/A]
• Version [1.2.2]

**Comment by KamilBeda** [comment]
I guess that docs on dynamic list in schema should be updated to use synchronous input with `false` input function parameter. Justin Schroeder suggested that this is better approach in discord. It would be great if dynamic list using schema docs also showed an example of field removing when this issue is resolved.
Docs page link - [https://formkit.com/inputs/list#dynamic-list-in-schema](https://formkit.com/inputs/list#dynamic-list-in-schema)

**Comment by justin-schroeder** [comment]
Phew — ok this actually isnt a bug. The issue was the `key` was placed at the root level of the `$el: 'div'`, which is not a valid location for the key, the key should be inside `attrs` (only the $formkit schema node hoists root level props/attrs into the `props` property).

Here is a working solution:

https://formkit.link/590f03feb56f85fc831fd7bb44907e67

And here is the non-schema version:

https://formkit.link/a75da562acf3b9be78b78d52c14bcb78

**Comment by KamilBeda** [comment]
Thank you for providing the clarification and examples. Sorry for misunderstanding this as a bug.

**Comment by justin-schroeder** [comment]
Ha, i thought it was a bug too mate. took me 30 minutes to figure out it wasn’t 👀
